DO $$
DECLARE
  v_course_id uuid;
  v_mod_id    uuid;
  v_l1 uuid; v_l2 uuid; v_l3 uuid; v_l4 uuid; v_l5 uuid; v_l6 uuid; v_lm uuid; v_lq uuid;
  v_quiz_id   uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ai-photography-practical-course';
  SELECT id INTO v_mod_id FROM modules WHERE course_id = v_course_id AND position = 10;
  SELECT id INTO v_l1 FROM lessons WHERE module_id = v_mod_id AND position = 1;
  SELECT id INTO v_l2 FROM lessons WHERE module_id = v_mod_id AND position = 2;
  SELECT id INTO v_l3 FROM lessons WHERE module_id = v_mod_id AND position = 3;
  SELECT id INTO v_l4 FROM lessons WHERE module_id = v_mod_id AND position = 4;
  SELECT id INTO v_l5 FROM lessons WHERE module_id = v_mod_id AND position = 5;
  SELECT id INTO v_l6 FROM lessons WHERE module_id = v_mod_id AND position = 6;
  SELECT id INTO v_lm FROM lessons WHERE module_id = v_mod_id AND position = 7;
  SELECT id INTO v_lq FROM lessons WHERE module_id = v_mod_id AND position = 8;

  DELETE FROM content_blocks WHERE lesson_id IN (v_l1,v_l2,v_l3,v_l4,v_l5,v_l6,v_lm,v_lq);

  -- ─── L10.1: Pricing with AI ───────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l1,'text',1,'{"html":"<h2>Pricing Your AI-Powered Photography Services</h2><p>AI editing changes your cost structure — the question is whether to pass savings to clients (volume strategy) or pocket efficiency gains while maintaining prices (margin strategy). There is a right answer for your market, and it is probably not the same as what photographers in London or New York do.</p><p>This lesson builds a pricing model calibrated to the Zambian professional photography market, taking into account local purchasing power, client expectations, and the competitive landscape.</p>"}'),
  (v_l1,'comparison_table',2,'{"headers":["Service","Traditional Turnaround","AI-Assisted Turnaround","Suggested Zambian Price (ZMW)"],"rows":[["Corporate headshots (10 images)","5–7 days","24 hours","ZMW 2,500–5,000"],["Wedding full day (300 images)","4–6 weeks","1–2 weeks","ZMW 15,000–30,000"],["Product shoot (20 images)","3–5 days","24–48 hours","ZMW 3,500–8,000"],["Real estate (15 images, HDR)","2–3 days","Same day","ZMW 2,000–4,500"],["Event coverage (100 images)","1–2 weeks","3–5 days","ZMW 4,000–10,000"],["Portrait family (20 images)","1 week","48 hours","ZMW 1,500–3,500"]]}'),
  (v_l1,'steps',3,'{"steps":[{"title":"Calculate Your True Cost Per Hour","body":"Add up: annual software subscriptions (Lightroom, Luminar Neo, Topaz, Kling AI) ÷ 12 months. Add equipment depreciation (camera body, lenses, drone at 3-year lifespan ÷ 36 months). Add fuel, data, and communication costs per shoot. Divide by the hours you work per month. This is your break-even hourly rate. Your pricing must exceed this to be sustainable."},{"title":"Value-Based Pricing Over Cost-Plus","body":"Do not price by hours. Price by the value you deliver. A product shot that helps a client sell more goods on their e-commerce site is worth a percentage of the sales it drives, not 3 hours of your time. Ask the client: ''What would it cost you if you did not have these images?'' Then price at a fraction of that answer."},{"title":"Premium Delivery Tiers","body":"Offer three tiers: Standard (full gallery, 5-day delivery), Priority (full gallery, 48-hour delivery, +50% on base price), and Rush (full gallery, same-day or next morning, +100%). AI editing makes Rush delivery genuinely viable. Most clients who book Rush will pay double — and the work takes you the same time."},{"title":"Retainer Agreements","body":"Pitch established businesses a monthly retainer: X shoots per month, guaranteed turnaround, priority booking. Price it at 10–20% above what they would pay booking individually. You get predictable income; they get priority access. AI editing makes you reliable enough to make and keep this promise."}]}'),
  (v_l1,'ai_prompt',4,'{"prompt":"I am a professional photographer in Lusaka, Zambia. My monthly fixed costs are: ZMW 800 software subscriptions, ZMW 600 equipment depreciation, ZMW 400 fuel and data. I want to earn ZMW 12,000 per month working 20 days a month, averaging 2 shoots per day. Help me build a simple pricing sheet for: corporate headshots, product photography, real estate, and event coverage. Include a Standard and Priority tier for each. Show me the maths.","tool":"Claude AI","label":"Build your personal Zambian photography pricing model"}');

  -- ─── L10.2: Client communication ─────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l2,'text',1,'{"html":"<h2>Client Communication: Delivering AI-Assisted Work Professionally</h2><p>The way you communicate about your AI workflow determines whether clients see it as a liability or an advantage. The wrong approach (hiding it, or over-explaining defensively) creates distrust. The right approach makes AI editing a selling point: faster delivery, better quality, consistent results.</p>"}'),
  (v_l2,'steps',2,'{"steps":[{"title":"Setting Expectations at Booking","body":"Include a one-paragraph ''Our Editing Process'' section in your booking confirmation email. State clearly that you use AI-assisted tools for culling, enhancement, and retouching. Frame it as a benefit: ''This means your gallery is delivered in [X days] instead of the industry-standard [Y days], with consistent quality across every image.'' Clients appreciate transparency and speed."},{"title":"Delivering the Gallery","body":"When you send the gallery link, include a 3–4 sentence delivery note: what was done, how to download, your revision policy, and a specific ask (''Reply to let me know which are your favourites — I''d love to see how you use them.''). This personalises the transaction and opens a feedback loop."},{"title":"Handling Revision Requests","body":"AI editing can create artefacts clients notice. Common complaints: ''the skin looks too smooth'', ''something looks wrong with the background''. Have a prepared response: ''I can adjust the retouching level — let me know if you prefer less skin smoothing or a more natural finish.'' Then make the revision quickly. Fast revisions make AI mistakes feel like a feature (fast service) not a bug."},{"title":"Upselling After Delivery","body":"After the client receives and approves their gallery, send a follow-up email 48 hours later: ''I noticed the brand colour palette you use — I have a 15-minute slot next week if you wanted a quick social media crop pack from today''s shoot. I can deliver 20 square crops optimised for Instagram within 24 hours for ZMW [price].'' AI makes it trivial to create derivative products from existing shoots."}]}'),
  (v_l2,'ai_prompt',3,'{"prompt":"Draft a professional client gallery delivery email for a Zambian commercial photographer. The shoot was corporate headshots for a Lusaka-based financial services company. 15 executives were photographed. The gallery contains 10 selects per person (150 total). Delivery is via a private Pixieset link. Include: a warm opening, what was delivered, download instructions, revision policy (2 rounds of revisions within 14 days), and a call to action to share favourites. Keep it under 200 words.","tool":"Claude AI","label":"Draft your gallery delivery email template"}');

  -- ─── L10.3: Social media machine ─────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l3,'text',1,'{"html":"<h2>Building a Social Media Machine with AI Photography</h2><p>Photographers with consistent, high-quality social media presence book more clients — not because of follower count, but because their portfolio is visible and up-to-date. The problem: consistent posting requires time most working photographers don''t have.</p><p>AI changes this. A single 2-hour shoot can generate 2–3 weeks of social media content with the right workflow. This lesson builds that system.</p>"}'),
  (v_l3,'steps',2,'{"steps":[{"title":"The One-Shoot, Many-Posts System","body":"From a single shoot, you can produce: (1) A hero image post (portrait, product shot, landscape). (2) A before/after post showing your AI editing process. (3) A carousel of 5–8 images from the same shoot. (4) A Reels clip using AI video animation from one of the stills. (5) A ''behind the scenes'' text post about the shoot. That is 5 posts from one session — 2–3 weeks of daily content if you post every 3 days."},{"title":"AI Caption Generation","body":"Do not write captions from scratch. Describe your image to Claude or ChatGPT and ask for: (1) A short punchy caption with 3 hashtags for Instagram. (2) A professional narrative for LinkedIn. (3) A conversational tone caption for Facebook. Three platforms, three tones, one prompt. Edit for your voice, then post."},{"title":"Scheduling with AI-Powered Tools","body":"Use Later, Buffer, or Meta Business Suite to schedule posts in advance. Spend 2 hours every Sunday preparing and scheduling content for the week. AI editing speed means you have enough content; scheduling means you do not need to think about it during shoot days."},{"title":"Hashtag Research","body":"For Zambia: #LusakaPhotographer, #ZambianPhotographer, #AfricanPhotography, #LusakaBusiness are audience-specific. Layer in category hashtags: #CommercialPhotography, #HeadshotPhotographer, #ProductPhotography, #AIPhotography. Do not exceed 10–15 hashtags on Instagram — beyond that, engagement rate drops."}]}'),
  (v_l3,'ai_prompt',4,'{"prompt":"I am a Zambian commercial photographer. I just finished a corporate headshot session for a mining company in the Copperbelt. I have 15 executive portraits. Help me create a 2-week social media content plan from this single shoot. For each post, give me: the content type (image type), the caption for Instagram (short, punchy, 3 hashtags), and the caption for LinkedIn (professional, longer). I post every 2–3 days.","tool":"Claude AI","label":"Generate 2 weeks of social media content from one shoot"}');

  -- ─── L10.4: Portfolio building ────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l4,'text',1,'{"html":"<h2>Portfolio Building: Showcasing AI-Assisted Work</h2><p>Your portfolio is your primary sales tool. A strong portfolio is not about showing everything you have shot — it is about showing the work that earns the clients you want. AI photography enables a portfolio refresh that would previously have taken months of new shoots: existing images can be re-edited, extended, and enhanced to a new quality level.</p>"}'),
  (v_l4,'steps',2,'{"steps":[{"title":"Audit Your Existing Portfolio","body":"Look at your current portfolio with fresh eyes: which images have weak backgrounds, flat light, or noise problems that AI can fix? Make a list. Prioritise the images that show your best composition and subject work but have technical weaknesses. These are your first re-edit targets — the structure is strong, the technical limitation is now fixable."},{"title":"Build Category-Specific Galleries","body":"Separate your portfolio by commercial category: Portraits, Products, Architecture, Events, Aerial. Each category page should show 8–12 images maximum. Quality over quantity — 8 perfect images outperform 30 average ones. Clients scan, not read. They make a decision within 15 seconds."},{"title":"Before/After Gallery","body":"Create a dedicated Before/After section on your website showing AI editing transformations. This is rare and demonstrates expertise. Most photographers hide their editing process. Showing it builds trust and differentiates you as someone who understands the full workflow, not just the camera."},{"title":"Case Study Page","body":"Add 2–3 brief case studies: [Client Type], [Brief], [What We Did], [Result]. These are more convincing than portfolio images alone because they show your thinking, not just your output. Use Claude to draft them from bullet points you provide — a 3-paragraph case study takes 5 minutes to write with AI assistance."}]}'),
  (v_l4,'ai_prompt',4,'{"prompt":"I want to write a case study for my photography portfolio website. The client was a Lusaka restaurant that needed new menu photography and social media images. I did a 3-hour product shoot, processed 200 images to 40 selects using AI culling, did background cleanup on 15 product shots using Photoshop Generative Fill, and colour-graded everything to a warm, appetising tone in Lightroom. The client used the images for a menu reprint and Instagram posts for 6 months. Write a 3-paragraph case study for my website.","tool":"Claude AI","label":"Draft a portfolio case study from your shoot notes"}');

  -- ─── L10.5: Studio operations ─────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l5,'text',1,'{"html":"<h2>Studio Operations: Running an Efficient AI-Powered Photography Business</h2><p>A photography business is not just about taking and editing pictures — it is a system of client management, file management, invoicing, and delivery. AI tools extend beyond image editing into business operations: contract generation, invoice creation, email drafting, and workflow automation.</p>"}'),
  (v_l5,'steps',2,'{"steps":[{"title":"File Naming and Archiving System","body":"Every shoot gets a folder: YYYY-MM-DD_ClientName_ShootType. Inside: /RAW, /Selects, /Edited, /Delivered. Never delete RAW files for 3 years — clients sometimes need reshoots that turn out not to be needed, or come back for additional images years later. Back up to two locations: an external drive and cloud storage (Google Drive, iCloud, or Backblaze B2 for photographers)."},{"title":"Client CRM","body":"A CRM (Customer Relationship Management) system tracks who your clients are, what they booked, when to follow up, and what their preferences are. For a solo photographer starting out, a Notion database or a simple Google Sheet works. For a growing practice, Táve, Honeybook, or Studio Ninja are photography-specific CRMs. AI can help you draft follow-up emails and proposals from CRM notes."},{"title":"Invoice Automation","body":"Create a standard invoice template and use Zoho Invoice (free tier) or Wave (free) to generate and send invoices. For Zambia, include your TPIN number on all business invoices. Set up automatic payment reminders at 3 days and 7 days overdue. AI can help you write a firm but professional late payment reminder if a client is unresponsive."},{"title":"Batch Processing Automation","body":"For high-volume work (events, real estate), use Lightroom''s Export Presets and Batch Export to process multiple images to multiple sizes simultaneously. Set up a ''Client Delivery Export'' preset: JPEG 95, sRGB, 4000px long edge, copyright watermark embedded, output to a ''Delivery'' folder. One click processes 200 images to client-ready files while you email the next booking inquiry."}]}'),
  (v_l5,'checklist',3,'{"items":["Standardised folder structure set up for every new shoot","RAW files backed up to external drive AND cloud storage","Client CRM or tracking spreadsheet set up","Invoice template created with TPIN and payment terms","Lightroom Client Delivery Export preset configured","Booking confirmation email template ready","Gallery delivery email template ready","AI Usage Policy clause added to client contract","Follow-up email template for upselling after delivery","Late payment reminder template ready"]}');

  -- ─── L10.6: Zambia income model ───────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l6,'text',1,'{"html":"<h2>The Zambia Income Model: Building Sustainable Revenue as an AI Photographer</h2><p>Photography income in Zambia has unique characteristics: seasonal peaks around December weddings and corporate end-of-year events, a growing B2B market in mining, NGOs, and banking, and an underserved demand for professional product photography from SMEs selling online.</p><p>This lesson maps the realistic income landscape and shows you how AI editing positions you to capture a premium segment of this market.</p>"}'),
  (v_l6,'case_study',2,'{"title":"Full-Time Lusaka Commercial Photographer — 12-Month Income Model","context":"A photographer with solid technical skills and this course''s AI workflow completes their first year of full-time commercial photography in Lusaka. They focus on: corporate clients (headshots, events), SME product photography, and 8–10 weddings per year.","action":"Monthly mix: 2 corporate headshot sessions (ZMW 3,500 each = ZMW 7,000), 4 product shoots (ZMW 4,500 each = ZMW 18,000), 1 event (ZMW 6,000), 1 wedding deposit or delivery payment (ZMW 12,000 average across 10 weddings spread over year). Total monthly target: ZMW 43,000 gross. After costs (software ZMW 1,800, fuel ZMW 800, equipment fund ZMW 2,000, NAPSA ZMW 1,200): ZMW 37,200 net — approximately USD 1,500 per month.","result":"This is achievable for a photographer with 2+ years of experience and this AI workflow within 6–12 months of focused client acquisition. The AI workflow is the multiplier: it enables faster delivery (justifying premium pricing), broader capacity (more shoots per month), and higher quality (justifying corporate rates). The alternative — manual editing — limits output to 1–2 shoots per week at lower rates."}'),
  (v_l6,'comparison_table',3,'{"headers":["Revenue Stream","ZMW/Month (Low)","ZMW/Month (High)","What Gets You to High"],"rows":[["Corporate headshots","5,000","15,000","Retainer agreements with 2–3 corporates"],["Product photography","6,000","24,000","E-commerce clients with monthly needs"],["Events","4,000","12,000","Consistent referral pipeline"],["Weddings (spread monthly)","4,000","20,000","Destination weddings, premium market"],["Stock/licensing","0","3,000","Consistent uploading to Adobe Stock"],["AI video add-on","0","8,000","Offering Reels video from stills as upsell"],["Online courses/presets","0","10,000","Packaging your expertise as a product"]]}'),
  (v_l6,'key_takeaway',5,'{"points":["The Lusaka commercial photography market can support a full-time AI photographer earning ZMW 25,000–50,000/month within 1–2 years with the right client mix.","AI editing is the operational advantage that makes premium pricing and fast delivery both possible simultaneously.","Diversifying across corporate, product, wedding, and digital revenue streams reduces the risk of any single market segment slowing down.","Your expertise in AI tools is itself a sellable product — presets, workshops, and online courses can eventually become income streams parallel to shooting."]}');

  -- ─── L10.M: Live Session 4 ───────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_lm,'text',1,'{"html":"<h2>Live Session 4: Business Strategy Clinic</h2><p>This is your fourth and final live session. In this session, your instructor will work through business strategy questions with you — pricing, client acquisition, portfolio positioning, and income planning specific to your situation and market.</p><p>Come with your real numbers, your real challenges, and your real questions. This is not a lecture — it is a working session.</p><h3>What to Prepare</h3><ul><li>Your current or target pricing for 2–3 services</li><li>Your biggest challenge in getting clients or closing bookings</li><li>Any question about the Zambia market, payment processing, or business structure</li></ul>"}'),
  (v_lm,'meeting',2,'{"meeting_id":"","title":"Live Session 4 — Business Strategy Clinic","start_time":""}'),
  (v_lm,'callout',3,'{"type":"info","title":"This Is Your Last Live Session","body":"Duration: 30 minutes. After this session, you move into the Final Module — the course review and final exam. This live session is your last opportunity for real-time personalised guidance from your instructor. Make the most of it by coming prepared with specific questions."}');

  -- ─── L10.Q: Quiz ─────────────────────────────────────────────────────────
  DELETE FROM quizzes WHERE lesson_id = v_lq;
  INSERT INTO content_blocks (lesson_id, type, position, content)
  VALUES (v_lq, 'quiz', 1, '{"quiz_id": ""}');

  INSERT INTO quizzes (lesson_id, title, description, passing_score, max_attempts)
  VALUES (v_lq, 'Module 10 Checkpoint — Business with AI', 'Test your knowledge of pricing, client communication, and business operations for AI photographers.', 80, 3)
  RETURNING id INTO v_quiz_id;

  UPDATE content_blocks
  SET content = jsonb_build_object('quiz_id', v_quiz_id::text)
  WHERE lesson_id = v_lq AND type = 'quiz';

  INSERT INTO quiz_questions (quiz_id, question, type, options, correct_answer, explanation, position) VALUES
  (v_quiz_id,
   'A client asks you to turn around their wedding gallery in 48 hours instead of the standard 2 weeks. You can do this with AI editing. How should you handle pricing?',
   'multiple_choice',
   '["Charge the same price — it is not fair to charge more just because you are faster","Decline — 48-hour wedding delivery is impossible","Add a Rush tier surcharge of 50–100% on top of the base price","Offer a discount for the inconvenience of rushing"]',
   'Add a Rush tier surcharge of 50–100% on top of the base price',
   'Rush delivery is a premium service that most clients will pay for without objection. Your AI workflow makes it operationally feasible, and the client values speed — price that value accordingly. Undercharging for rush work devalues the capability.',
   1),
  (v_quiz_id,
   'When building a portfolio, what is the recommended number of images per category page?',
   'multiple_choice',
   '["As many as possible — volume shows experience","30–50 images to demonstrate range","8–12 high-quality images — quality over quantity","At least 100 to fill a professional-looking gallery"]',
   '8–12 high-quality images — quality over quantity',
   'Clients make portfolio decisions within 15 seconds of scanning. A tightly curated gallery of 8–12 perfect images communicates quality and selectivity. Padding with average images dilutes the impression.',
   2),
  (v_quiz_id,
   'Which of the following best describes the AI editing workflow''s impact on a Lusaka photographer''s business?',
   'multiple_choice',
   '["It allows lower pricing to win more volume clients","It enables faster delivery and higher quality simultaneously, justifying premium pricing","It replaces the need for shooting skill with editing skill","It eliminates the need for client communication since delivery is automated"]',
   'It enables faster delivery and higher quality simultaneously, justifying premium pricing',
   'AI editing''s primary business value is the combination of speed and quality — two things that traditionally traded off against each other. This combination justifies premium pricing and allows a solo photographer to compete at a corporate level.',
   3),
  (v_quiz_id,
   'What is a retainer agreement in photography, and what is its primary benefit for the photographer?',
   'multiple_choice',
   '["An agreement where the client pays only after delivery — lower risk for both parties","A monthly agreement where a business pays a fixed fee for a set number of shoots — providing predictable income","A legal protection agreement covering AI disclosure","An insurance policy covering equipment during shoots"]',
   'A monthly agreement where a business pays a fixed fee for a set number of shoots — providing predictable income',
   'Retainers convert unpredictable per-shoot income into monthly recurring revenue. For a solo photographer, this predictability allows better financial planning, equipment investment, and the ability to turn down less profitable work.',
   4),
  (v_quiz_id,
   'From a single 2-hour product shoot with 200 RAW images, what is the realistic amount of social media content you can generate using the AI workflow described in this module?',
   'multiple_choice',
   '["1–2 posts maximum","5 posts: hero image, before/after, carousel, AI video Reels clip, and behind-the-scenes text","Unlimited — AI can generate content indefinitely from a single image","Only posts for platforms where you have an existing audience"]',
   '5 posts: hero image, before/after, carousel, AI video Reels clip, and behind-the-scenes text',
   'The one-shoot, many-posts system generates 5 content pieces per session: a hero image post, a before/after edit reveal, a carousel of selects, a Reels clip animated with Kling AI, and a text post about the shoot. That is 2–3 weeks of content posted every 3 days.',
   5);

  RAISE NOTICE '✓ Module 10 (Business with AI Photography) content loaded.';
END $$;
