-- ============================================================
-- Module 2 Content: AI Background Removal
-- ============================================================
DO $$
DECLARE
  v_course_id uuid; v_mod_id uuid;
  v_l1 uuid; v_l2 uuid; v_l3 uuid; v_l4 uuid; v_l5 uuid; v_l6 uuid;
  v_lm uuid; v_lq uuid; v_quiz_id uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ai-photography-practical-course';
  SELECT id INTO v_mod_id FROM modules WHERE course_id = v_course_id AND position = 2;
  SELECT id INTO v_l1 FROM lessons WHERE module_id = v_mod_id AND position = 1;
  SELECT id INTO v_l2 FROM lessons WHERE module_id = v_mod_id AND position = 2;
  SELECT id INTO v_l3 FROM lessons WHERE module_id = v_mod_id AND position = 3;
  SELECT id INTO v_l4 FROM lessons WHERE module_id = v_mod_id AND position = 4;
  SELECT id INTO v_l5 FROM lessons WHERE module_id = v_mod_id AND position = 5;
  SELECT id INTO v_l6 FROM lessons WHERE module_id = v_mod_id AND position = 6;
  SELECT id INTO v_lm FROM lessons WHERE module_id = v_mod_id AND position = 7;
  SELECT id INTO v_lq FROM lessons WHERE module_id = v_mod_id AND position = 8;
  DELETE FROM content_blocks WHERE lesson_id IN (v_l1,v_l2,v_l3,v_l4,v_l5,v_l6,v_lm,v_lq);

  -- ── L2.1: How semantic segmentation works ──────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l1, 'text', 1, '{"html": "<h2>Why AI Background Removal Works So Well</h2><p>For 30 years, cutting a subject from a background required manual selection tools — magic wand, lasso, pen path, or channels. A skilled retoucher could spend 40 minutes on a single portrait with complex hair. AI has changed this completely, and the reason is a technique called semantic segmentation.</p><p>Semantic segmentation is the AI task of classifying every pixel in an image into a named category: person, hair, sky, grass, building, car. Unlike simple colour-based selection (which fails the moment subject and background share similar tones), semantic segmentation understands what things are — not just what colour they are.</p>"}'),
  (v_l1, 'expert_note', 2, '{"title": "Deep Dive: How Segmentation Models Are Trained", "body": "Segmentation models like the one inside Remove.bg are trained on datasets where human annotators have manually drawn precise masks around subjects in hundreds of thousands of images. The model learns to predict these masks for new images it has never seen.\n\nModern tools use encoder-decoder architectures (like U-Net) or transformer-based models (like SAM — Segment Anything Model from Meta). The encoder extracts feature maps from the image at multiple scales. The decoder uses these features to predict a per-pixel segmentation mask.\n\nHair is notoriously difficult because individual strands are semi-transparent and fine. Tools that handle hair well have been trained specifically on hair datasets with fine-grained annotations, sometimes at sub-pixel precision using alpha compositing.\n\nThe quality gap between tools often comes down to: (1) the size and quality of training data, (2) whether the model was trained on your specific subject type (people, products, animals, etc.), and (3) post-processing steps like edge refinement and alpha matting."}'),
  (v_l1, 'comparison_table', 3, '{"title": "AI Background Removal Tools Compared", "headers": ["Tool", "Best For", "Hair Handling", "Batch Support", "Free Tier", "Cost"], "rows": [["Remove.bg", "People, products, animals", "Excellent", "Yes (desktop app)", "50 low-res/month", "Credits from $0.20/image"], ["Photoshop AI (Select Subject)", "Complex compositing", "Very good", "Via Actions/Scripts", "Photoshop subscription", "Included in PS plan"], ["Canva Background Remover", "Social media content", "Good", "One at a time", "Limited", "Included in Canva Pro"], ["Photoroom", "Product photography", "Good", "Yes", "5 exports/month", "From $9.99/month"], ["Background Eraser App (mobile)", "Quick social use", "Basic", "No", "Limited", "From $2.99/month"]]}'),
  (v_l1, 'key_takeaway', 4, '{"title": "Segmentation — What You Need to Know", "points": ["AI background removal works because it understands what objects are, not just their colour. This is why it beats the magic wand tool.", "Hair is the hardest challenge. Tools specifically trained on hair datasets (Remove.bg, Photoshop) handle it far better than general-purpose tools.", "AI performs best when there is clear spatial separation between subject and background. Composition choices before the shoot directly affect AI removal quality.", "Semi-transparent fabrics (veil, lace, glass) and reflective surfaces (jewellery) are edge cases where manual refinement is still needed after AI removal.", "Always do a final edge check at 100% zoom before delivering cutouts to clients."]}');

  -- ── L2.2: Remove.bg walkthrough ────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l2, 'text', 1, '{"html": "<h2>Remove.bg — The Complete Guide</h2><p>Remove.bg is the fastest route from a raw photo to a clean PNG cutout. It requires no installation, no Photoshop subscription, and no technical knowledge. The web interface handles portraits, products, animals, cars, and complex objects. The desktop app and API add batch processing and workflow integration.</p>"}'),
  (v_l2, 'steps', 2, '{"title": "Remove.bg Full Workflow", "steps": [{"title": "Web Tool — Your First Cutout", "body": "Go to remove.bg in any browser. Drag your photo onto the upload area or click Upload Image. The AI processes in 2-5 seconds. The result appears with a transparent background. Use the Download button to save. Free tier: low-resolution PNG with no watermark — good enough for web and social use."}, {"title": "Edge Refinement — When AI Needs Help", "body": "Click Edit in the result view to open the refinement tools. Use the Erase brush to remove remaining background fragments. Use the Restore brush to bring back subject areas the AI accidentally removed (common around fine hair edges). Zoom to 100% before final download to catch any issues."}, {"title": "Adding a New Background", "body": "In the Edit view, click the Background tab. Choose from the built-in colour fills and textures, or upload your own background image. The tool composites your cutout onto the new background. This is useful for quick client previews — show a product on white, then on a lifestyle background, all from the same cutout."}, {"title": "Desktop App — Batch Processing", "body": "Download the free Remove.bg Desktop App (Mac or Windows). Drag a folder of photos onto the app window. It processes all images automatically and saves cutouts to an output folder. Credit cost is the same per image. This is the workflow for processing 20-50 images from a product shoot or event."}, {"title": "API — Full Automation", "body": "For studio workflows processing hundreds of images, the Remove.bg API allows integration with your own scripts or tools. With basic knowledge of any programming language, you can build a fully automated pipeline: ingest RAW exports, process all images, and save cutouts — with zero manual interaction."}]}'),
  (v_l2, 'ai_prompt', 3, '{"label": "Background Concept Generator", "tool": "ChatGPT", "prompt": "I am a photographer in Zambia. I have just cut out a portrait subject using Remove.bg. The subject is [describe: corporate professional / wedding couple / student / product]. Suggest 8 creative background options that would work well for this subject, suitable for my market. For each background, describe: the visual concept, the mood it creates, the type of client it suits, and whether I can create it easily in Lightroom, Photoshop, or using a free image from Unsplash."}'),
  (v_l2, 'checklist', 4, '{"title": "Remove.bg Quality Checklist", "items": ["Zoomed to 100% and checked all edges of the cutout", "Checked hair and fine detail edges specifically", "Checked any areas where subject colour is similar to background", "Used erase/restore brush on any problem areas", "Downloaded at full resolution (not just the preview)", "Verified the PNG transparency opens correctly in the destination app"]}');

  -- ── L2.3: Photoshop AI Selection ───────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l3, 'text', 1, '{"html": "<h2>Photoshop AI Selection: The Professional Approach</h2><p>For photographers already in the Adobe ecosystem, Photoshop offers AI selection tools that integrate directly into a full compositing workflow. The advantage over Remove.bg is control: Photoshop gives you the full power of the application after you make the selection, enabling non-destructive editing, layer adjustments, and advanced compositing on the same cutout.</p><p>There are three main AI selection tools in Photoshop: Select Subject (for the main subject), Select Sky (for landscape/outdoor shots), and the full AI Masking Panel (for selective refinements).</p>"}'),
  (v_l3, 'steps', 2, '{"title": "Photoshop AI Background Removal — Step by Step", "steps": [{"title": "Open Your Image", "body": "Open your photo in Photoshop. Create a duplicate layer (Ctrl/Cmd+J) to preserve the original."}, {"title": "Select Subject", "body": "Go to Select > Subject. Photoshop AI analyses the image and creates a selection around the main subject. This takes 2-5 seconds. You will see the marching ants selection outline appear."}, {"title": "Open Select and Mask", "body": "With the selection active, go to Select > Select and Mask. This opens the refinement workspace. Set the View mode to On Black or On White to clearly see edge quality."}, {"title": "Refine the Edge", "body": "Use the Refine Edge Brush tool (the second tool in the toolbar) and paint along hair and fine-detail edges. Photoshop applies edge detection that recovers fine strands against the background. Increase Edge Detection Radius for complex hair."}, {"title": "Output the Mask", "body": "In the Output To dropdown, choose Layer Mask. Click OK. Your subject is now on a layer with a non-destructive mask — you can always edit the mask later without reprocessing."}, {"title": "Remove Background", "body": "Select the Background layer and delete it, or simply hide it. You now have a cutout ready for compositing. Place it above a new background layer or export as PNG with transparency."}]}'),
  (v_l3, 'comparison_table', 3, '{"title": "Remove.bg vs Photoshop AI Selection", "headers": ["Aspect", "Remove.bg", "Photoshop Select Subject"], "rows": [["Speed", "5 seconds — fastest", "20-60 seconds with refinement"], ["Control", "Limited — web-based editing only", "Full Photoshop compositing available"], ["Hair quality", "Excellent for portraits", "Excellent with Select and Mask refinement"], ["Batch processing", "Desktop app handles batches", "Requires Action and Batch automation setup"], ["Software needed", "None — browser only", "Photoshop subscription ($10+/month)"], ["Non-destructive", "No — produces flat PNG", "Yes — layer mask is fully editable"], ["Best use case", "Quick deliverables, web, social", "Professional compositing, print, studio work"]]}'),
  (v_l3, 'callout', 4, '{"variant": "tip", "title": "Use Both Tools — They Have Different Strengths", "body": "Remove.bg for speed on volume work (product photography, headshot batches). Photoshop for precision on hero images (wedding composites, fine-art portraits, print advertising). You do not have to choose one — most professional photographers use both depending on the job."}');

  -- ── L2.4: Canva background remover ────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l4, 'text', 1, '{"html": "<h2>Canva Background Remover — For Social Content</h2><p>Canva is not a professional photo editor. But for photographers who create their own social media content, marketing materials, or client presentations, the Canva background remover is a practical tool that fits into an existing design workflow without switching applications.</p><p>Canva Pro includes AI background removal directly inside the design tool. You upload a photo, click Background Remover, and immediately have a cutout you can layer onto any Canva design — social post, price list, portfolio page, or client proposal.</p>"}'),
  (v_l4, 'steps', 3, '{"title": "Canva Background Remover Workflow", "steps": [{"title": "Upload Your Photo to Canva", "body": "In any Canva design, click Uploads in the left sidebar and upload your portrait or product photo."}, {"title": "Place the Photo in Your Design", "body": "Click your uploaded photo to add it to the canvas. Resize and position it."}, {"title": "Apply Background Remover", "body": "With the photo selected, click Edit Image in the top toolbar, then Background Remover. Canva processes and removes the background in about 5-10 seconds."}, {"title": "Refine if Needed", "body": "Use the Erase and Restore brushes (available in the same panel) to clean up any problem areas."}, {"title": "Layer Over Your Design", "body": "Your cutout now sits transparently over the Canva design background. You can place it over any colour, gradient, or design element."}]}'),
  (v_l4, 'tool_spotlight', 2, '{"name": "Canva Pro", "description": "Design platform with built-in AI background remover, image upscaling, and AI text generation. Particularly useful for photographers who create their own social media content, pricing guides, or client-facing design materials alongside their photography.", "url": "https://www.canva.com/pro", "icon_url": ""}'),
  (v_l4, 'checklist', 4, '{"title": "Canva Use Cases for Photographers", "items": ["Instagram posts: portrait cutout on a branded colour background", "Price list design: headshot of photographer over a clean background", "Client proposal: product photos cut out and placed in a presentation", "Portfolio thumbnails: consistent background colour across all preview images", "Email header: your photo over a branded gradient"]}');

  -- ── L2.5: Batch removal ────────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l5, 'text', 1, '{"html": "<h2>Batch Background Removal at Scale</h2><p>For product photographers, headshot photographers, and anyone delivering more than 20 cutouts at a time, processing images one by one is not a workflow — it is a bottleneck. Batch processing automates removal across an entire folder while you work on something else.</p>"}'),
  (v_l5, 'steps', 2, '{"title": "Three Batch Approaches", "steps": [{"title": "Option A: Remove.bg Desktop App (Easiest)", "body": "Download the Remove.bg Desktop App for Mac or Windows (free download, credit cost per image). Open the app. Drag your entire export folder onto the app window. It processes every image automatically and saves clean PNGs to an output folder. Credit cost: approximately $0.20 per image. Processing speed: 2-5 seconds per image. For 50 images: around 3-5 minutes total."}, {"title": "Option B: Photoshop Batch Action (Most Control)", "body": "Record a Photoshop Action: (1) Select > Subject, (2) Select > Select and Mask > Output as Layer Mask, (3) Delete Background Layer, (4) File > Export As PNG, (5) Close. Then run: File > Automate > Batch. Choose your action and your source folder. Photoshop processes every image and saves a PNG. No credit cost — only Photoshop subscription. Slower per image but free after setup."}, {"title": "Option C: Photoroom Studio (Product Focus)", "body": "Photoroom Studio allows batch upload of product photos via their web platform. Drag in your folder, it removes backgrounds and can apply a standardised background template across the entire batch. Excellent for e-commerce product photography where all images need the same output format."}]}'),
  (v_l5, 'callout', 3, '{"variant": "warning", "title": "Plan Your Credit Budget Before Batch Jobs", "body": "At $0.20 per image, a 200-image product shoot costs $40 in Remove.bg credits. Always check your credit balance before starting a large batch. Consider the Photoshop batch action approach for high volumes where per-image credit cost adds up significantly."}'),
  (v_l5, 'expert_note', 4, '{"title": "API-Based Automation for Advanced Users", "body": "For photographers building a studio workflow or software product on top of background removal, the Remove.bg API allows full programmatic control.\n\nA basic Python script can:\n1. Loop through a folder of images\n2. POST each image to the Remove.bg API\n3. Save the returned PNG to an output folder\n4. Log results and flag failures\n\nThis approach costs the same per image as the desktop app but integrates with any custom workflow — including Lightroom plugin pipelines, order management systems, or gallery delivery tools.\n\nPhotoroom and Clipping Magic also offer APIs with similar capabilities. Compare pricing and quality on your specific image types before committing to one provider."}');

  -- ── L2.6: Difficult cuts ───────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l6, 'text', 1, '{"html": "<h2>Difficult Cuts: Hair, Glass, and Transparent Fabrics</h2><p>AI background removal is impressively accurate on clear subjects against contrasting backgrounds. But three types of subjects consistently cause problems: fine hair (especially fly-aways and curly hair), transparent or translucent materials (glass, veil, lace), and reflective surfaces (jewellery, mirrors, water). Understanding why these fail — and how to fix them — is what separates a professional result from an obvious AI cutout.</p>"}'),
  (v_l6, 'case_study', 2, '{"title": "Wedding Veil on a Garden Background", "context": "A photographer in Lusaka needed to cut out a bride wearing a floor-length veil against a garden background. The veil was white on a green hedge background — similar enough that the AI partially removed sections of the veil and left some hedge showing through where the veil was transparent.", "action": "The photographer used Remove.bg for the initial cut (which handled the non-veil areas perfectly), then opened the result in Photoshop. Using the Refine Edge brush on the veil area with a high Radius setting, the AI edge detection recovered most of the veil transparency. The remaining hedge fragments were manually erased with a soft low-opacity brush. Total additional refinement time: 8 minutes.", "result": "Final image quality was indistinguishable from a manual pen-tool cut. Total time including AI removal and refinement: 11 minutes. Manual pen-tool approach for the same image would have taken 35-45 minutes."}'),
  (v_l6, 'steps', 3, '{"title": "Troubleshooting Difficult Cuts", "steps": [{"title": "Hair: Fly-Aways and Curly Texture", "body": "Use Remove.bg or Photoshop first. For remaining fly-away hair problems, open in Photoshop Select and Mask and increase the Smart Radius. Paint with the Refine Edge Brush along the hair outline. If individual strands are still lost, you have two options: (1) use a very small brush in Photoshop to manually restore strands, or (2) accept the result — most clients viewing at normal size cannot tell the difference."}, {"title": "Glass and Transparent Objects", "body": "AI struggles with glass because the model cannot distinguish between the glass and the background it shows through. For product photos of bottles or glasses: shoot against a white background (maximise contrast for the glass outline). AI removes the background from the shape. Then manually paint back partial transparency on the glass body using a layer mask at 50-70% opacity — this creates a believable see-through effect."}, {"title": "Reflective Jewellery", "body": "Jewellery reflects its background, which confuses edge detection. Shoot jewellery against a very neutral grey or white background with consistent lighting (no harsh reflections). After AI removal, manually clean any background colour cast from reflective surfaces using the Hue/Saturation tool in Photoshop targeted to the background colour that was picked up."}, {"title": "Lace and Net Fabric", "body": "Lace is semi-transparent and its holes create complex edge profiles. Remove.bg often treats the holes as background and fills them. In Photoshop, use the Channels panel — find the channel with the most contrast between subject and background, Ctrl-click to load as a selection, and use this as your starting mask. Refine with Select and Mask."}]}'),
  (v_l6, 'callout', 4, '{"variant": "tip", "title": "Shoot to Make AI Easier", "body": "The single most powerful thing you can do to improve AI background removal quality is to control the shoot. For product photography: white or grey seamless. For portraits: walls or backgrounds with clear contrast from skin tone and clothing. The 5 minutes spent choosing a better background location saves 20 minutes of post-production refinement."}');

  -- ── L2.7: Live Session 1 (Meeting) ────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_lm, 'text', 1, '{"html": "<h2>Live Session 1: AI Tool Setup and Background Removal Workshop</h2><p>This is your first live session with your instructor. Bring your questions, bring a photo you have been struggling to cut out, and come ready to work through problems in real time.</p><p>Topics covered in this session:</p><ul><li>Common setup issues with Remove.bg, Photoshop AI, and Topaz Photo AI</li><li>Live demonstration of a complex background removal (fine hair, difficult background)</li><li>Q&A: your specific photos and use cases</li><li>Personal workflow recommendations based on your shoot types and volume</li></ul>"}'),
  (v_lm, 'meeting', 2, '{"meeting_id": "", "title": "Live Session 1: AI Tool Setup and Background Removal Workshop", "start_time": "TBD — check course announcements for scheduled date", "description": "30-minute live session covering tool setup, background removal demo, and personal Q&A. Bring a photo you want to work on."}'),
  (v_lm, 'checklist', 3, '{"title": "Prepare Before the Session", "items": ["Remove.bg account created and logged in", "Topaz Photo AI trial downloaded and installed", "Adobe Lightroom or Photoshop installed and working", "One photo ready to share for live demonstration — ideally one you found difficult", "Questions written down — have at least 2 specific questions ready", "Stable internet connection confirmed"]}');

  -- ── Module 2 Checkpoint Quiz ────────────────────────────────────────────
  DELETE FROM quizzes WHERE lesson_id = v_lq;
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES (v_lq, 'quiz', 1, '{"quiz_id": ""}');
  INSERT INTO quizzes (lesson_id, title, pass_threshold, max_attempts)
    VALUES (v_lq, 'Module 2: AI Background Removal', 70, 3) RETURNING id INTO v_quiz_id;
  UPDATE content_blocks SET content = jsonb_build_object('quiz_id', v_quiz_id::text)
    WHERE lesson_id = v_lq AND type = 'quiz';

  INSERT INTO quiz_questions (quiz_id, question, options, correct_indices, explanation, position) VALUES
    (v_quiz_id, 'What makes AI background removal more reliable than the magic wand selection tool?',
     '["AI processes faster on modern hardware", "AI understands what objects are (semantic segmentation) rather than just matching colours", "AI uses higher bit-depth processing", "The magic wand tool is no longer available in Photoshop"]',
     '{1}', 'Semantic segmentation classifies every pixel by what it represents, not by colour. This is why AI handles complex hair and fine edges far better than colour-based selection.', 1),
    (v_quiz_id, 'A photographer needs to remove backgrounds from 80 product photos. Which approach is most efficient?',
     '["Process each image individually on remove.bg website", "Use the Remove.bg desktop app to batch-process the entire folder", "Use the Photoshop pen tool for maximum quality control", "Send the images to an offshore retoucher"]',
     '{1}', 'The Remove.bg desktop app accepts a full folder and processes all images automatically. This is the most efficient approach for medium-volume batch work.', 2),
    (v_quiz_id, 'What is the main advantage of Photoshop Select Subject over Remove.bg?',
     '["It is faster and completely free", "It produces a non-destructive layer mask that allows full Photoshop compositing after removal", "It handles transparent fabrics better than any other tool", "It does not require a subscription"]',
     '{1}', 'Photoshop outputs a layer mask, meaning you keep all compositing options within the full Photoshop environment. Remove.bg produces a flat PNG that has limited further editing options.', 3),
    (v_quiz_id, 'What is the most effective thing you can do before a shoot to improve AI background removal quality?',
     '["Use a mirrorless camera instead of a DSLR", "Set a higher ISO to improve subject clarity", "Choose a shoot location or background with clear contrast against your subject", "Shoot in RAW format instead of JPEG"]',
     '{2}', 'Clear contrast between subject and background is the biggest predictor of AI removal quality. Composition decisions before the shoot directly affect post-production efficiency.', 4),
    (v_quiz_id, 'A photographer cuts out a portrait but the AI has removed a section of the subject''s dark jacket because it matched the dark background. The best fix is:',
     '["Re-shoot the portrait against a lighter background", "Use the Restore brush in Remove.bg or Photoshop to paint back the removed jacket area", "Accept the result — AI cannot handle dark subjects on dark backgrounds", "Use a different colour space (Adobe RGB instead of sRGB)"]',
     '{1}', 'Both Remove.bg and Photoshop Select and Mask have a Restore brush that paints back subject areas that the AI incorrectly removed. This is a quick fix for partial subject removal.', 5);

  RAISE NOTICE '✓ Module 2 content loaded (6 lessons + meeting + quiz).';
END $$;
