-- ============================================================
-- Module 4 Content: AI Enhancement — Noise, Sharpness, Quality Recovery
-- ============================================================
DO $$
DECLARE
  v_course_id uuid; v_mod_id uuid;
  v_l1 uuid; v_l2 uuid; v_l3 uuid; v_l4 uuid; v_l5 uuid; v_l6 uuid; v_lq uuid;
  v_quiz_id uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ai-photography-practical-course';
  SELECT id INTO v_mod_id FROM modules WHERE course_id = v_course_id AND position = 4;
  SELECT id INTO v_l1 FROM lessons WHERE module_id = v_mod_id AND position = 1;
  SELECT id INTO v_l2 FROM lessons WHERE module_id = v_mod_id AND position = 2;
  SELECT id INTO v_l3 FROM lessons WHERE module_id = v_mod_id AND position = 3;
  SELECT id INTO v_l4 FROM lessons WHERE module_id = v_mod_id AND position = 4;
  SELECT id INTO v_l5 FROM lessons WHERE module_id = v_mod_id AND position = 5;
  SELECT id INTO v_l6 FROM lessons WHERE module_id = v_mod_id AND position = 6;
  SELECT id INTO v_lq FROM lessons WHERE module_id = v_mod_id AND position = 7;
  DELETE FROM content_blocks WHERE lesson_id IN (v_l1,v_l2,v_l3,v_l4,v_l5,v_l6,v_lq);

  -- ── L4.1: Digital noise explained ────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l1, 'text', 1, '{"html": "<h2>Why High ISO Looks the Way It Does</h2><p>Every photographer has experienced it: a photo taken at an indoor event, low available light, ISO pushed to 6400 or 12800 — and the result is a grainy, noisy image that looks usable on a phone screen but falls apart when you zoom in. Understanding why digital noise happens is the first step to understanding how AI eliminates it so effectively.</p><p>Digital noise comes from the electronic process of capturing light on a sensor. When light is scarce (low light or fast shutter speed), each photosite (pixel cell) on the sensor receives fewer photons. With fewer photons, random variation in the signal becomes proportionally larger — this is the noise. It is fundamentally a signal-to-noise ratio problem.</p><p>There are two types of noise: <strong>luminance noise</strong> (the grainy, film-like texture that affects brightness) and <strong>chroma noise</strong> (the coloured speckles — red, green, blue blotches — that look distinctly digital and unpleasant). Luminance noise is often tolerable or even stylistically desirable. Chroma noise is rarely acceptable in client-facing work.</p>"}'),
  (v_l1, 'expert_note', 2, '{"title": "Deep Dive: How AI Denoising Actually Works", "body": "Traditional noise reduction works by blurring: average nearby pixels together to smooth out the random variation. The problem is that blurring also smooths out genuine detail — fine texture, skin pores, fabric weave, hair strands. This is why traditional NR always involves a sharpness-versus-noise tradeoff.\n\nAI denoising works differently. Models like those in Topaz Photo AI were trained on pairs of images: a clean, low-ISO image and the same image artificially degraded with noise at various levels. The model learned to predict what the clean version looked like given the noisy input.\n\nWhen the model encounters a real noisy image, it does not blur — it predicts. It asks: given this pattern of noise, what is the most likely true pixel value here? For areas of skin, it knows skin has smooth tonal transitions with fine texture. For hair, it knows hair has fine linear detail. For fabric, it knows textile weave patterns.\n\nThis is why AI denoising preserves detail that traditional NR destroys: the model is not blurring, it is predicting the clean signal from a learned understanding of what real-world subjects look like.\n\nThe practical limit: if noise is severe enough that genuine signal is completely lost (very high ISO, very dark exposure, extreme crops), even AI cannot recover detail that was never captured. AI enhances signals that exist; it cannot fabricate signals that do not."}'),
  (v_l1, 'comparison_table', 3, '{"title": "Noise Characteristics by ISO Level", "headers": ["ISO", "Luminance Noise", "Chroma Noise", "AI Recoverability", "Client-Ready?"], "rows": [["ISO 800", "Minimal", "None", "Excellent — minor NR", "Yes, without AI"], ["ISO 1600", "Visible at 100%", "Slight", "Excellent", "Yes, basic NR"], ["ISO 3200", "Clearly visible", "Noticeable", "Very good — AI needed", "With AI: yes"], ["ISO 6400", "Heavy", "Significant", "Good — AI essential", "With AI: usually yes"], ["ISO 12800", "Very heavy", "Heavy", "Moderate — depends on subject", "With AI: sometimes"], ["ISO 25600+", "Severe", "Severe", "Limited — some detail lost", "With AI: marginal"]]}'),
  (v_l1, 'key_takeaway', 4, '{"title": "Noise and AI Recovery", "points": ["Luminance noise (grain) is tolerable in some contexts; chroma noise (coloured speckles) is rarely acceptable.", "AI denoising predicts the clean signal — it does not blur. This preserves detail that traditional NR destroys.", "ISO 6400 is recoverable to client-ready quality with Topaz Photo AI on most modern sensors.", "Your shooting technique matters: exposure to the right (ETTR) reduces noise by capturing more photons per pixel.", "Batch denoising with AI means you no longer need to avoid high ISO — shoot for the moment, fix in post."]}');

  -- ── L4.2: Topaz Photo AI walkthrough ────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l2, 'tool_spotlight', 1, '{"name": "Topaz Photo AI", "description": "The industry-leading AI tool for noise reduction, lens blur correction, and image upscaling. Trained on millions of images across different camera sensors and noise profiles. Available as standalone software or as a plugin inside Lightroom and Photoshop. One-time purchase — no ongoing subscription.", "url": "https://www.topazlabs.com/topaz-photo-ai", "icon_url": ""}'),
  (v_l2, 'steps', 2, '{"title": "Topaz Photo AI — Complete Workflow", "steps": [{"title": "Open Your Image", "body": "Drag a RAW or JPEG onto the Topaz Photo AI window. For RAW files, Topaz reads the file directly and applies processing to the full-resolution data — not a JPEG conversion. This is important for quality."}, {"title": "Autopilot Mode", "body": "Click the Autopilot button. Topaz analyses the image and automatically recommends: which models to activate (Denoise, Sharpen, or Upscale), and at what strength. For most photographers in most situations, Autopilot produces excellent results without manual adjustment."}, {"title": "Manual Model Selection", "body": "If Autopilot is not optimal, manually configure: (1) Denoise — choose Normal (standard noise), Low Light (severe noise from very high ISO), or Severe Noise. Adjust Strength (0-100) and Detail (how much fine detail to preserve). (2) Sharpen — choose Motion Blur, Out of Focus, or Standard Sharpen. (3) Upscale — choose the desired output size (2x, 4x, 6x)."}, {"title": "Preview at 100%", "body": "Always zoom to 100% before committing. Toggle the before/after comparison. Check: skin texture preserved? Hair strands intact? Fabric detail retained? Adjust model strength down if over-processed (plastic skin is worse than grain)."}, {"title": "Export", "body": "Click Save Image. Choose format: TIFF (16-bit for further processing in Lightroom/PS), JPEG (final delivery), or DNG (if you want to continue as a RAW file). For Lightroom integration, use the Lightroom plugin: right-click the image > Edit In > Topaz Photo AI. It opens, processes, and returns a TIFF to your Lightroom catalog automatically."}, {"title": "Batch Processing", "body": "Select multiple images (or drag a folder) onto the Topaz window. Apply the same settings or use Autopilot individually per image. Click Save All. Batch runs in the background — go edit another image or have coffee."}]}'),
  (v_l2, 'callout', 3, '{"variant": "tip", "title": "ISO 6400 is No Longer a Problem", "body": "With Topaz Photo AI, images previously unusable for client delivery become portfolio quality. Stop avoiding high ISO at events and in low light — shoot for the moment and fix the noise in post. The AI handles it better than you could manually in half the time."}'),
  (v_l2, 'callout', 4, '{"variant": "warning", "title": "Avoid Over-Processing", "body": "Reducing Detail strength too low or setting Strength too high produces plastic-looking skin with no texture. A slight amount of remaining grain is always more natural than zero grain. Target results that look like a clean low-ISO image — not a watercolour painting."}');

  -- ── L4.3: LR Denoise vs Topaz ────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l3, 'text', 1, '{"html": "<h2>Lightroom AI Denoise vs Topaz Photo AI</h2><p>Adobe Lightroom (version 12.3 and later) includes AI Denoise as a built-in feature — accessible directly from the Develop module. For photographers already in Lightroom, this raises the question: when do you use Lightroom AI Denoise, and when do you go to Topaz?</p><p>The honest answer: Lightroom AI Denoise is excellent and handles most situations well. Topaz is better in specific scenarios — very high ISO, severe noise, or when you need precise control over which noise model is applied. For most photographers doing most of their work below ISO 6400, Lightroom AI Denoise is sufficient and faster to access.</p>"}'),
  (v_l3, 'comparison_table', 2, '{"title": "Lightroom AI Denoise vs Topaz Photo AI", "headers": ["Aspect", "Lightroom AI Denoise", "Topaz Photo AI"], "rows": [["Access", "Built into Lightroom — one click", "Separate application or plugin"], ["Cost", "Included in Lightroom subscription", "One-time purchase (~$199 or ~$99/yr)"], ["Speed", "Fast on Apple Silicon / modern GPU", "Fast — GPU accelerated"], ["Quality at ISO 3200-6400", "Excellent", "Excellent — slight edge in detail"], ["Quality at ISO 12800+", "Good", "Better — more model options"], ["Upscaling", "Lightroom Super Resolution (good)", "Topaz Gigapixel (excellent)"], ["Control", "One slider (Amount)", "Multiple models and fine controls"], ["Workflow integration", "Native — stays in LR catalog", "Plugin round-trip to LR catalog"], ["Best use", "Standard event and portrait work", "High-ISO events, print, upscaling for large format"]]}'),
  (v_l3, 'case_study', 3, '{"title": "Event Photographer — Choosing the Right Tool", "context": "A Lusaka event photographer regularly shoots corporate dinners and award ceremonies at ISO 3200-8000. They wanted to know whether to use Lightroom AI Denoise or invest in Topaz Photo AI.", "action": "Tested both tools on 20 images at ISO 3200, 6400, and 12800 from a recent event. Evaluated at 100% zoom for: skin texture preservation, chroma noise elimination, and processing time per image.", "result": "At ISO 3200-6400: results were nearly identical. Lightroom was faster to access. At ISO 8000-12800: Topaz produced noticeably cleaner results with better texture preservation. Decision: use Lightroom AI Denoise as the default for standard event work (saves the Topaz round-trip time). Use Topaz for any image at ISO 8000+ and for all images destined for large print."}'),
  (v_l3, 'key_takeaway', 4, '{"title": "The Decision Framework", "points": ["Use Lightroom AI Denoise for: ISO under 6400, standard web and social delivery, volume work where speed matters.", "Use Topaz Photo AI for: ISO 8000+, print work, upscaling for large format, any image where maximum quality is essential.", "Both tools produce RAW-quality output — you are not sacrificing quality by staying in Lightroom for standard work.", "If you are on a tight budget: Lightroom AI Denoise covers 80% of use cases. Topaz is an investment that pays off over time if you regularly shoot in challenging light."]}');

  -- ── L4.4: Motion blur and missed focus ──────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l4, 'text', 1, '{"html": "<h2>Recovering Motion Blur and Missed Focus</h2><p>AI can fix noise. Can it fix blur? The answer is: sometimes, and the extent depends on the severity of the blur and the subject type. Understanding the limits helps you decide when to attempt AI sharpening and when to move on to the next frame.</p><p>Topaz Photo AI has two distinct sharpening models: <strong>Motion Blur</strong> (for camera shake or subject movement during exposure) and <strong>Out of Focus</strong> (for missed focus, where the subject is soft but the background is sharp). These are different problems with different AI solutions.</p>"}'),
  (v_l4, 'steps', 2, '{"title": "Sharpening Workflow in Topaz Photo AI", "steps": [{"title": "Identify the Blur Type", "body": "Look at the image carefully. Is the blur directional — streaks in one direction? That is motion blur (camera shake or subject movement). Is the blur uniform and soft in all directions? That is out-of-focus blur. The blur type determines which model to select."}, {"title": "Apply Motion Blur Model", "body": "In Topaz Photo AI, under Sharpen, select Motion Blur. Set Strength to 50 (start conservative). Preview at 100%. Increase Strength if more correction is needed. High Strength values can introduce halos around edges — reduce if this appears."}, {"title": "Apply Out of Focus Model", "body": "Select Out of Focus sharpen. This model attempts to reconstruct the in-focus version of a soft subject. Results are best when the subject is slightly soft (missed by 5-20cm). Severely out-of-focus images (subject visually blurry at normal viewing) cannot be fully recovered."}, {"title": "Combine with Denoise", "body": "Blur recovery often reveals noise that was hidden by the blur. After sharpening, add the Denoise model to clean up the recovered detail. Preview the combination before exporting."}, {"title": "Set Your Acceptance Threshold", "body": "Not every blurry image is recoverable. Your standard: would a client be satisfied viewing this at normal gallery size on a laptop screen? If yes after AI correction, it is deliverable. If still obviously soft at normal viewing, move to the next frame from the burst."}]}'),
  (v_l4, 'expert_note', 3, '{"title": "The Physics of Blur Recovery — What AI Can and Cannot Do", "body": "Motion blur represents lost information: during the exposure, the image moved and you captured an average of all positions. AI sharpening attempts to reverse this averaging — but the information is genuinely absent from the file.\n\nFor mild blur (subject moved slightly), AI can convincingly reconstruct a sharp version because the original signal is mostly preserved with manageable averaging. For severe blur, AI is essentially interpolating across missing data — the reconstruction is a prediction, not a recovery. The result may look sharper but is not genuinely recovering real detail.\n\nOut-of-focus blur is somewhat different: the information is present in the file but optically smeared by the lens. AI can model the lens point-spread function (how the out-of-focus lens spreads a point of light) and reverse the process. This works better than motion blur recovery for mild cases.\n\nPractical limit: if the subject is visibly blurry at normal screen viewing size before AI correction, and AI does not make it client-acceptable at normal size, move on to the next frame."}'),
  (v_l4, 'callout', 4, '{"variant": "important", "title": "Burst Mode is Still Your Best Safety Net", "body": "AI sharpening is a recovery tool for occasional failures, not a substitute for camera technique. In dynamic situations — children, sports, dancing — shoot burst mode and cull to the sharpest frame. AI sharpening is for the one shot you cannot replace: the decisive moment, the first dance, the winning goal."}');

  -- ── L4.5: Topaz Gigapixel / upscaling ───────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l5, 'text', 1, '{"html": "<h2>AI Upscaling for Print: Topaz Gigapixel Deep Dive</h2><p>Traditional image upscaling (bicubic, Lanczos) works by interpolating between existing pixels — essentially guessing what value should go between two known values. The result is soft when printed large because there is no real detail being added.</p><p>AI upscaling — specifically Topaz Gigapixel AI — works differently. The model was trained on pairs of high-resolution and downscaled images. It learned to hallucinate plausible fine detail when upscaling: it does not interpolate between known values, it predicts what texture and edge detail should realistically exist in the gaps based on the subject type it recognises.</p><p>The result: a 12MP photo upscaled 4x to ~48MP equivalent can be printed at A1 size (594 x 841mm / approximately 24 x 33 inches) without obvious pixelation at normal viewing distance. This opens print revenue streams that many photographers with older or smaller-sensor cameras previously could not access.</p>"}'),
  (v_l5, 'steps', 2, '{"title": "Gigapixel AI Upscaling Workflow", "steps": [{"title": "When to Upscale", "body": "Use Gigapixel for: images destined for large print (A2, A1, or larger), crops where you need to enlarge a small section of a larger image, phone camera images for professional use, older camera RAW files for current print standards."}, {"title": "Choose the Right Scale Factor", "body": "2x upscale: A4 photo to A2 print. 4x upscale: A4 photo to near-A0 print. 6x upscale: maximum, for very large format. Start at 2x or 4x — diminishing returns exist above this range."}, {"title": "Select the Correct Model", "body": "Standard: general photography. High Fidelity: when preserving fine micro-detail is critical (product, architecture). Low Resolution: for heavily pixelated inputs (old phone photos, screen grabs). Art and CG: for illustrations and graphics (not relevant to photography)."}, {"title": "Suppress Noise Before Upscaling", "body": "Enable the built-in noise suppression or process through Topaz Photo AI Denoise first. Upscaling amplifies noise along with detail — clean files produce dramatically cleaner upscaled results."}, {"title": "Evaluate and Export", "body": "Preview the result at screen resolution. Export as TIFF (16-bit if further editing in Photoshop is needed) or JPEG at maximum quality. Send the exported TIFF to your print lab at the correct DPI (300 DPI for standard quality, 240 DPI minimum for fine art print)."}]}'),
  (v_l5, 'expert_note', 3, '{"title": "Understanding Print Resolution Requirements", "body": "Print quality is measured in DPI (dots per inch). The relationship between pixel dimensions and print size:\n\n300 DPI (professional standard): Image must have 300 pixels per inch of print area.\nA4 print (210 x 297mm / 8.27 x 11.69 inches): needs 2481 x 3507 pixels — about 8.7MP.\nA3 print (420 x 594mm): needs 4961 x 7016 pixels — about 34MP.\nA2 print (594 x 841mm): needs 7016 x 9933 pixels — about 69MP.\nA1 print (841 x 1189mm): needs 9933 x 14043 pixels — about 140MP.\n\nA 24MP camera (6000 x 4000px) prints comfortably at A3 at 300DPI. For A2, you are at 213 DPI — acceptable but not optimal for close-viewing fine art print.\n\nGigapixel 4x upscales a 24MP file to ~384MP equivalent resolution — theoretically printable at A0 (841 x 1189mm) at 300 DPI. In practice, results depend on the original image quality, but A1 and A2 from AI-upscaled 24MP images are regularly professional-quality."}'),
  (v_l5, 'checklist', 4, '{"title": "Before You Send to Print", "items": ["Upscaled at the correct factor for the target print size (calculate: target pixels needed at 300 DPI)", "Applied noise reduction before upscaling", "Exported at 300 DPI, TIFF or high-quality JPEG", "Converted to the correct colour profile for your print lab (sRGB for most labs, Adobe RGB if specified)", "Checked the upscaled result at 100% zoom for any upscaling artifacts (halos, unnatural textures)", "Ordered a small test print before committing to a large canvas order"]}');

  -- ── L4.6: Batch enhancement pipeline ─────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l6, 'text', 1, '{"html": "<h2>Building an Automated Batch Enhancement Pipeline</h2><p>Enhancing images one by one in Topaz Photo AI is faster than manual methods, but it is still interactive. A true batch pipeline runs while you sleep — you set it up before bed, and in the morning your enhanced files are ready for grading and delivery.</p>"}'),
  (v_l6, 'steps', 2, '{"title": "The Overnight Enhancement Pipeline", "steps": [{"title": "Step 1: Export Culled Selections from Lightroom", "body": "After culling and creative selection, export your keeper set as TIFFs (16-bit) to a dedicated folder: /Projects/ShootName/Enhancement_Input/. Do not export as JPEG at this stage — you want the full data for enhancement."}, {"title": "Step 2: Configure Topaz Batch Settings", "body": "Open Topaz Photo AI. Drag the Enhancement_Input folder onto the window. All images load as a batch. Set preferences: Autopilot On (or configure manual settings if you know this shoot has consistent noise issues). Output format: TIFF 16-bit. Output folder: Enhancement_Output/."}, {"title": "Step 3: Start Overnight Batch", "body": "Click Save All. Let the batch run. GPU-accelerated processing handles 5-15 images per minute depending on resolution and complexity. A 300-image set typically finishes in 30-60 minutes. Schedule this before bed or during a meeting."}, {"title": "Step 4: Import Enhanced Files to Lightroom", "body": "In Lightroom, go to File > Import Photos. Navigate to Enhancement_Output/ and import the processed TIFFs. These appear alongside your originals in the catalog. Apply your grade preset to the enhanced set."}, {"title": "Step 5: Quality Check and Deliver", "body": "Review 10-15% of images at 100% to confirm AI results. Flag any that need manual adjustment (rare with Autopilot). Export at delivery resolution and deliver."}]}'),
  (v_l6, 'ai_prompt', 3, '{"label": "Workflow Automation Advisor", "tool": "ChatGPT", "prompt": "I am a photographer building a batch enhancement pipeline using Topaz Photo AI and Lightroom Classic. My typical workflow: I cull in AfterShoot, export RAW keepers from Lightroom, run Topaz batch overnight, then import enhanced TIFFs back to Lightroom for grading.\n\nI want to speed this up further. Please suggest:\n1. Any Lightroom plugins or scripts that can automate the export-to-Topaz-folder step\n2. Whether a Lightroom Export Preset can save my enhancement folder location and settings\n3. How to set up a Lightroom Smart Collection that automatically filters enhanced TIFFs from originals\n4. Any free tools that can watch a folder and trigger Topaz processing automatically\n5. What hardware upgrade would have the biggest impact on batch processing speed (RAM, GPU, or faster storage)"}'),
  (v_l6, 'key_takeaway', 4, '{"title": "Batch Enhancement — The Business Case", "points": ["A properly set up batch pipeline requires zero active time — it runs while you work on other clients or sleep.", "Consistently enhanced galleries look more professional than selective enhancement — every image is sharp and clean.", "The investment: 30 minutes of setup per shoot type, then 0 active time per job.", "GPU matters: an Nvidia RTX or Apple M-series chip dramatically speeds batch processing. If you batch regularly, this is a hardware investment worth making.", "Enhancement does not replace shooting well — it turns marginally acceptable images into clean deliverables. It cannot rescue fundamentally wrong exposures or severe blur."]}');

  -- ── Module 4 Checkpoint Quiz ──────────────────────────────────────────
  DELETE FROM quizzes WHERE lesson_id = v_lq;
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES (v_lq, 'quiz', 1, '{"quiz_id": ""}');
  INSERT INTO quizzes (lesson_id, title, pass_threshold, max_attempts)
    VALUES (v_lq, 'Module 4: AI Enhancement', 70, 3) RETURNING id INTO v_quiz_id;
  UPDATE content_blocks SET content = jsonb_build_object('quiz_id', v_quiz_id::text)
    WHERE lesson_id = v_lq AND type = 'quiz';

  INSERT INTO quiz_questions (quiz_id, question, options, correct_indices, explanation, position) VALUES
    (v_quiz_id, 'What is the fundamental difference between AI denoising and traditional noise reduction?',
     '["AI is faster and uses less processing power", "Traditional NR blurs pixels to average out noise; AI predicts what the clean signal should look like based on learned patterns", "AI denoising works on JPEG files; traditional NR only works on RAW", "There is no meaningful difference — AI NR is just a marketing name for traditional methods"]',
     '{1}', 'Traditional NR blurs pixels, destroying detail. AI denoising predicts the original clean signal from learned knowledge of real-world subjects, preserving texture.', 1),
    (v_quiz_id, 'Which scenario would most benefit from Topaz Photo AI over Lightroom AI Denoise?',
     '["ISO 1600 portrait for Instagram", "ISO 800 product photo for e-commerce", "ISO 12800 wedding reception image destined for a 60x90cm print", "ISO 3200 headshot for LinkedIn"]',
     '{2}', 'Very high ISO combined with a large print destination is the scenario where Topaz Photo AI''s superior detail preservation and additional model options provide the most benefit over Lightroom.', 2),
    (v_quiz_id, 'Why should you run noise reduction BEFORE colour grading?',
     '["Noise reduction requires the original RAW data which colour grading permanently changes", "Colour adjustments in grading can amplify chroma noise, and clean files grade more accurately", "Lightroom does not allow AI Denoise after presets have been applied", "Colour grading adds a colour profile that interferes with AI model selection"]',
     '{1}', 'Colour grading — especially in shadows and saturated areas — can amplify chroma noise. Denoising first produces a clean canvas that grades more accurately and consistently.', 3),
    (v_quiz_id, 'Topaz Gigapixel AI can upscale a 24MP image to what approximate size for professional print?',
     '["48MP — sufficient for A2 at 240 DPI (4x upscale)", "384MP — theoretically sufficient for A0 at 300 DPI (4x upscale)", "96MP — sufficient for A1 at 300 DPI (2x upscale)", "12MP — Gigapixel downsamples for print clarity"]',
     '{1}', 'A 4x upscale multiplies pixel dimensions by 4 in each direction (16x total pixel count). 24MP x 16 = 384MP equivalent, providing printable quality at very large format.', 4),
    (v_quiz_id, 'A photographer wants to process 200 portrait images overnight in Topaz Photo AI. What is the correct setup?',
     '["Open each image individually, apply settings, save, then open the next", "Configure batch settings and output folder, drag the full folder into Topaz, click Save All, let it process overnight", "Export as JPEG first, then batch in Topaz", "AI batch processing requires a cloud subscription — local batch is not available"]',
     '{1}', 'Topaz Photo AI supports folder-based batch processing. Drag the folder in, configure settings once, click Save All. It runs autonomously and produces output to a specified folder.', 5);

  RAISE NOTICE '✓ Module 4 content loaded (6 lessons + quiz).';
END $$;
