DO $$
DECLARE
  v_course_id uuid;
  v_mod_id    uuid;
  v_l1 uuid; v_l2 uuid; v_l3 uuid; v_l4 uuid; v_l5 uuid; v_lq uuid;
  v_quiz_id   uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ai-photography-practical-course';
  SELECT id INTO v_mod_id FROM modules WHERE course_id = v_course_id AND position = 9;
  SELECT id INTO v_l1 FROM lessons WHERE module_id = v_mod_id AND position = 1;
  SELECT id INTO v_l2 FROM lessons WHERE module_id = v_mod_id AND position = 2;
  SELECT id INTO v_l3 FROM lessons WHERE module_id = v_mod_id AND position = 3;
  SELECT id INTO v_l4 FROM lessons WHERE module_id = v_mod_id AND position = 4;
  SELECT id INTO v_l5 FROM lessons WHERE module_id = v_mod_id AND position = 5;
  SELECT id INTO v_lq FROM lessons WHERE module_id = v_mod_id AND position = 6;

  DELETE FROM content_blocks WHERE lesson_id IN (v_l1,v_l2,v_l3,v_l4,v_l5,v_lq);

  -- ─── L9.1: AI video from stills — Kling AI and Runway ───────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l1,'text',1,'{"html":"<h2>AI Video From Stills: Kling AI and Runway ML</h2><p>The frontier of AI photography is no longer just about images — it''s about <strong>animating them</strong>. With tools like Kling AI and Runway ML, a single well-composed photograph can become a 5-second cinematic clip: clouds drift, hair moves in a breeze, a product rotates, a landscape comes alive.</p><p>For photographers, this unlocks a new revenue stream: delivering social media video content from a stills shoot, without owning or operating video equipment.</p>"}'),
  (v_l1,'comparison_table',2,'{"headers":["Feature","Kling AI","Runway ML Gen-3"],"rows":[["Image-to-video quality","Excellent for natural motion (people, nature)","Excellent for abstract and stylised motion"],["Duration per clip","Up to 10 seconds","Up to 10 seconds"],["Camera motion control","Pan, zoom, orbit presets","Custom camera path"],["Photorealism","Very high — faces hold up","High — occasional artefacts on faces"],["Resolution output","1080p","1080p / 4K (Pro)"],["Pricing (approx.)","Subscription or credits","Subscription — $15/mo standard"],["Zambia access","Web-based, accessible","Web-based, accessible"]]}'),
  (v_l1,'steps',3,'{"steps":[{"title":"Kling AI — Animate a Portrait","body":"Go to klingai.com and sign in. Select Image to Video. Upload your portrait JPEG. In the Motion Intensity slider, set to Low (2–3) for subtle, natural movement — high values create exaggerated warping. In the Prompt field, describe the motion: ''gentle breeze moves hair, subject breathes naturally, subtle head turn''. Select 5 seconds and 1080p. Generate and download."},{"title":"Runway — Add Camera Motion","body":"Open Runway Gen-3 Alpha. Create new project, select Image to Video. Upload your still. Under Camera Motion, select a preset (Slow push in, Arc left, etc.) or draw a custom camera path. Add a text prompt for any subject motion. Generate. Runway gives you more camera control than Kling but slightly less subject realism."},{"title":"Delivering Video for Clients","body":"Export the AI video as MP4 H.264 at highest quality. Pair with your original still in a combined social media package: a high-res JPEG for print/web use and a 5–10 second video clip for Instagram Reels, LinkedIn, or TikTok. This doubles the perceived value of a single shooting session."},{"title":"What to Avoid","body":"Do not animate complex group shots — faces in the background degrade. Do not use AI video for real estate (creates legal liability if motion misrepresents the property). Do not exceed 5 seconds for portrait work — longer clips reveal artefacts. Disclose AI animation to clients in your delivery terms."}]}'),
  (v_l1,'tool_spotlight',4,'{"name":"Kling AI","purpose":"Photorealistic image-to-video animation for portraits, products, and landscapes","url":"https://klingai.com","pros":["Highly realistic face animation","Natural motion physics (hair, fabric, water)","Accessible from Zambia via web browser","Affordable credit-based pricing"],"cons":["Occasional temporal flickering on fine detail","Cannot reliably animate multiple people","Export limited to 10 seconds per generation"]}'),
  (v_l1,'expert_note',5,'{"title":"The Motion Budget — Why Less Is More","body":"The biggest mistake beginners make with AI video is over-animating. A subtle 3-second drift of a subject''s eyes and gentle chest movement reads as cinematic life. Full body movement, dramatic camera swoops, and complex actions expose every limitation of the model. Professional videographers know motion calls attention — so calls attention to artefacts. Build your AI animation instinct around restraint: animate what the eye notices first (face, breath, hair), leave the rest still."}');

  -- ─── L9.2: Portrait relighting ───────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l2,'text',1,'{"html":"<h2>Portrait Relighting with AI</h2><p>You captured the perfect expression but the light was wrong — too flat, too harsh, wrong direction for the mood. Before AI relighting, this meant a reshoot. Now, tools like Adobe Lightroom''s AI-powered Light panel, Photoshop''s Neural Filters (Depth Blur + Smart Portrait), and dedicated tools like Portrait AI can repositionally relight a portrait after the fact.</p><p>This is one of the most technically complex and impressive things AI can do in post-production — and it''s available in tools photographers already own.</p>"}'),
  (v_l2,'steps',2,'{"steps":[{"title":"Lightroom AI Masking for Light Direction","body":"In Lightroom, open the Masking panel (Shift+W). Select Subject. In Lightroom Classic 12+ or the new Lightroom, use the Light panel''s Directional Light controls (if your version supports it) to add a directional light source. Adjust Intensity, Warmth, and Position (clock face slider for direction). This adds a soft, AI-estimated directional light to the subject mask only."},{"title":"Photoshop Neural Filters — Depth Blur","body":"Open your portrait in Photoshop. Go to Filter > Neural Filters > Depth Blur. Enable Bokeh and Light Source. Use the Light Source Direction wheel to specify where the light comes from. Increase Hazing to add atmospheric depth. This filter estimates scene depth from the image and applies blur and lighting appropriate to depth position."},{"title":"Luminar Neo Portrait Relighting","body":"In Luminar Neo, open Relight AI from the tools panel. Use the Brightness of Near Objects slider to control foreground subject brightness independently. Use Brightness of Far Objects for background. The AI separates depth planes and allows independent brightness and colour control by depth zone — useful for separating a subject from a dark background or lightening a shaded face."},{"title":"Fixing Mixed Colour Temperature After Relighting","body":"After any AI relighting, check for colour temperature mismatches — the AI may add a warm key light while the original ambient light was cool. Use Lightroom''s Mixer (HSL panel) or a Colour Balance adjustment layer in Photoshop to blend the temperatures. The goal is one dominant colour temperature with a subtle contrast accent, not two competing casts."}]}'),
  (v_l2,'ai_prompt',3,'{"prompt":"I have a portrait where my subject was lit by a large window on their left side, but the light was very flat — no shadow, no depth, no drama. I''m in Photoshop with Luminar Neo also available. Walk me through the most effective approach to add the impression of a Rembrandt-style lighting pattern to this portrait in post. What are the tools, steps, and limits of this approach?","tool":"Claude AI","label":"Get a custom relighting strategy for your specific image"}'),
  (v_l2,'callout',4,'{"type":"warning","title":"The Uncanny Valley of Relighting","body":"AI relighting works best when the change is subtle — shifting flat light to soft directional light. When you try to radically change light direction (e.g. from right to left key light), shadows fall in physically impossible directions and the image enters uncanny valley territory. Use AI relighting to enhance existing light, not reverse it."}');

  -- ─── L9.3: HDR merging ───────────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l3,'text',1,'{"html":"<h2>HDR Merging with AI Tone Mapping</h2><p>High Dynamic Range (HDR) photography captures detail in both blown highlights and crushed shadows by bracketing 3–5 exposures and merging them. The challenge has always been tone mapping: making the merged image look natural rather than the garish, over-processed HDR that was fashionable in the 2000s and is now a mark of amateur work.</p><p>AI-powered HDR merging in Lightroom and Photoshop produces ghost-free, natural-looking HDR that retains the photographic quality of a single-exposure RAW file — without the HDR ''look''.</p>"}'),
  (v_l3,'steps',2,'{"steps":[{"title":"Bracket Your Exposures Correctly","body":"For interior architecture or landscape, bracket 3 exposures: -2 EV (for highlights), 0 EV (base exposure), +2 EV (for shadows). Use a tripod and 2-second timer or remote shutter to eliminate camera shake between frames. If shooting a moving subject (people, trees in wind), use Auto Exposure Bracketing (AEB) at the highest continuous frame rate to minimise motion between frames."},{"title":"Merge in Lightroom (Recommended)","body":"Select your bracketed exposures in Lightroom. Right-click > Photo Merge > HDR. In the HDR Merge Preview, enable Auto Align (for handheld brackets) and Auto Settings. Set Deghost Amount to Medium for most scenes — this detects and corrects moving elements (people, foliage) between frames. Click Merge. Lightroom creates an HDR DNG with 32-bit depth — you can now apply all standard adjustments with enormous dynamic range."},{"title":"Tone Mapping the HDR DNG","body":"After merge, your HDR DNG will look flat — this is normal. It contains far more dynamic range than a standard file. In the Tone Curve, create a mild S-curve to add contrast. Use Highlights slider all the way down (-100) and Shadows up (+80). The result should look like a naturally exposed scene with detail in all areas — not the HDR look."},{"title":"Architecture Interiors — the Key Use Case","body":"HDR is most professionally valuable for interior architecture: rooms with windows showing bright outdoor views alongside dark indoor spaces. Shoot 5 brackets at 1 EV intervals (-2, -1, 0, +1, +2) and merge. The AI deghosting handles any people walking through the frame. This is a standard deliverable for real estate and hospitality photography clients."}]}'),
  (v_l3,'expert_note',3,'{"title":"When to Use Single-Exposure AI Recovery Instead of HDR","body":"Lightroom''s Highlight Recovery and Shadow Recovery sliders, powered by AI in recent versions, can now recover up to 4 stops of highlight detail from a RAW file without bracketing. For most outdoor scenes, this is sufficient — and shooting a single exposure is always faster and more reliable than bracketing. HDR bracketing is genuinely necessary when: the dynamic range exceeds 5 stops (bright window in a dark room), you are shooting architecture for a commercial client who needs window detail, or you need to hold detail in both a lit interior and a bright exterior simultaneously."}'),
  (v_l3,'callout',4,'{"type":"info","title":"Lightroom AI Auto Tone vs Manual HDR Tone Mapping","body":"When you click ''Auto Settings'' on an HDR DNG, Lightroom''s AI analyses the histogram and applies a tone mapping that works for most images in seconds. For client work, start with Auto Settings and refine from there — the AI''s starting point is usually 70–80% of the way to a final result, saving significant time on each image."}');

  -- ─── L9.4: Drone enhancement ─────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l4,'text',1,'{"html":"<h2>Drone Image Enhancement with AI</h2><p>Drone cameras have improved dramatically but still lag behind full-frame sensors in dynamic range, sharpness, and low-light performance. AI post-processing can close much of this gap — turning a technically limited drone JPEG into a print-quality aerial image.</p><p>This lesson covers the specific workflow for drone imagery, where the challenges (small sensor noise, compressed dynamic range, lens distortion, haze) are different from ground-level photography.</p>"}'),
  (v_l4,'steps',2,'{"steps":[{"title":"Shoot RAW (Not JPEG) on Your Drone","body":"Enable RAW capture on your DJI or Autel drone before flying. RAW files give you 2–4 extra stops of dynamic range to work with compared to the drone''s JPEG, which is already tone-mapped in-camera. If your drone only supports JPEG, enable D-Log or D-Cinelike colour profile to preserve more information in the file."},{"title":"Atmospheric Haze Removal","body":"Aerial images shot from altitude in hazy conditions (common in the dry season in Zambia) lose contrast and saturation at distance. In Lightroom, use the Dehaze slider (20–40%) to cut through haze. In Photoshop, Filter > Camera Raw Filter > Dehaze. Do not over-dehaze — the horizon will look artificially sharp and alien."},{"title":"AI Upscaling for Print","body":"Drone images from consumer drones (DJI Mini 4 Pro: 48MP, DJI Air 3: 50MP) are sufficient for most web use but may need upscaling for large print. Use Lightroom''s Enhance > Super Resolution (AI 4× upscale) or Topaz Gigapixel AI. A 48MP drone image upscaled 4× becomes a 192MP file — printable at A0 at 300 DPI."},{"title":"Lens Distortion and Geometric Correction","body":"Wide-angle drone lenses create barrel distortion visible on building edges and horizon lines. In Lightroom, enable Lens Corrections > Enable Profile Corrections and select your drone model. For manual correction, use Transform > Guided Upright and click 4 points along a straight line that should be straight (building edge, horizon). This straightens converging lines that make architecture look warped."},{"title":"AI Noise Reduction for Low-Light Drone Footage","body":"Drone sensors at ISO 400+ show significant noise, especially in shadow areas. Apply Lightroom Denoise (Enhance > Denoise) at 40–60 for typical drone ISO. For DJI footage shot at dusk or dawn (ISO 800+), denoise at 70–85. Always check that ground textures (rooftops, foliage) retain realistic detail after denoising — over-processing creates a plastic appearance."}]}'),
  (v_l4,'tool_spotlight',3,'{"name":"Topaz Gigapixel AI","purpose":"AI-powered image upscaling for print-quality enlargements from drone and other small-sensor cameras","url":"https://topazlabs.com/gigapixel","pros":["4× to 6× upscaling with genuine detail synthesis","Specific models for faces, art, and low-resolution sources","Lightroom plugin integration","One-time purchase option"],"cons":["Slow on older hardware without dedicated GPU","Very large output files (100MB+ for 4× upscale)","Can hallucinate detail on very low-quality sources"]}'),
  (v_l4,'case_study',4,'{"title":"Real Estate Aerial — Lusaka Property Shoot","context":"A real estate agency commissioned aerial photography of a gated estate development in Lusaka. The drone (DJI Mini 3) produced sharp images of the buildings, but the dry-season haze reduced the Kafue River visible 8km in the background to a grey smear. The client specifically wanted the river visible as a selling point for the development.","action":"Dehaze at 35% in Lightroom restored the river''s colour and definition. Targeted HSL Luminance adjustments boosted blue (sky and river) and reduced yellow (hazy air colour). A targeted radial gradient on the background area with slight sharpening and clarity boost added distance definition without affecting the foreground buildings.","result":"The river was clearly visible and attractive in the final images without looking over-processed. The client used the aerial as their primary marketing image and reported higher click-through rates on property listing ads compared to previous developments photographed without the enhancement. Total editing time: 8 minutes per image."}');

  -- ─── L9.5: Print optimisation ─────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l5,'text',1,'{"html":"<h2>Print Optimisation: Getting Your AI-Edited Images Ready for Print</h2><p>Screen editing and print output are fundamentally different. Your monitor emits light; printed paper reflects it. Colours that pop on screen may look dull in print. Details that appear sharp at 100% zoom may look soft at 300 DPI. AI editing creates additional complications: upscaled images, generatively filled regions, and heavily denoised skin all behave differently in print than they appear on screen.</p><p>This lesson prepares you to deliver print-ready files your clients can take directly to a professional lab.</p>"}'),
  (v_l5,'steps',2,'{"steps":[{"title":"Soft Proofing in Lightroom","body":"Before exporting, enable Soft Proofing in Lightroom (shortcut: S in Develop mode). Select the colour profile for your client''s print lab (e.g. sRGB, AdobeRGB, or the lab''s custom ICC profile if they provide one). Lightroom simulates how the image will look when printed to that profile. Adjust until the soft-proof version looks correct — then export using that profile."},{"title":"Resolution Check for Print Size","body":"For print at 300 DPI: A4 (21×29cm) requires 2480×3508 px. A3 (29×42cm) requires 3508×4961 px. A2 (42×59cm) requires 4961×7016 px. Check your image resolution in Lightroom (Library module, Metadata panel > Dimensions). If too small, use Lightroom Super Resolution or Topaz Gigapixel AI before exporting."},{"title":"Sharpening for Print","body":"In Lightroom Export, set Sharpening to: Screen for web, Low for small prints (A5–A4), Standard for medium prints (A3–A2), High for large prints (A1 and above). Print sharpening in Lightroom is output-aware — it calculates the correct sharpening amount for the specified DPI and media type (Matte vs Glossy)."},{"title":"Export Settings for Lab Submission","body":"Export as TIFF (16-bit) for professional labs that accept TIFF. For labs that require JPEG: Quality 95–100, sRGB colour space, no metadata stripping (embed your copyright). File size for a TIFF A3 image will typically be 80–150MB. Compress the folder and use a file transfer service (WeTransfer, Google Drive) to send to the lab."},{"title":"AI-Filled Areas in Print","body":"Areas filled with Photoshop Generative Fill or extended with Generative Expand may show compression artefacts or tonal inconsistency at high print magnification. After generative editing, view the affected areas at 200% zoom and apply mild Gaussian blur (0.3–0.5 px) if you see pixel-level artefacts. This is only necessary for very large prints — A3 and below typically show no issues."}]}'),
  (v_l5,'key_takeaway',3,'{"points":["Soft proofing in Lightroom is the single most important step for preventing print colour disappointment — always proof before export.","AI-upscaled images print well but may require additional output sharpening — Topaz Gigapixel AI includes a sharpening step at export.","Export as TIFF-16bit for maximum print quality; use JPEG quality 95+ only if the lab does not accept TIFF.","Check Generative Fill regions at 200% before sending to print — artefacts invisible on screen can appear at high print magnification."]}');

  -- ─── L9.Q: Quiz ──────────────────────────────────────────────────────────
  DELETE FROM quizzes WHERE lesson_id = v_lq;
  INSERT INTO content_blocks (lesson_id, type, position, content)
  VALUES (v_lq, 'quiz', 1, '{"quiz_id": ""}');

  INSERT INTO quizzes (lesson_id, title, description, passing_score, max_attempts)
  VALUES (v_lq, 'Module 9 Checkpoint — Advanced Tools', 'Test your knowledge of AI video, relighting, HDR, drone editing, and print optimisation.', 80, 3)
  RETURNING id INTO v_quiz_id;

  UPDATE content_blocks
  SET content = jsonb_build_object('quiz_id', v_quiz_id::text)
  WHERE lesson_id = v_lq AND type = 'quiz';

  INSERT INTO quiz_questions (quiz_id, question, type, options, correct_answer, explanation, position) VALUES
  (v_quiz_id,
   'When using Kling AI to animate a portrait, why is a Low motion intensity setting (2–3) recommended over High?',
   'multiple_choice',
   '["Low settings are faster to generate","Low settings preserve photorealism — high values create exaggerated warping that exposes AI limitations","Low settings use fewer credits","High settings are reserved for landscape animation only"]',
   'Low settings preserve photorealism — high values create exaggerated warping that exposes AI limitations',
   'High motion intensity in AI video generators reveals model limitations: faces warp, anatomy becomes distorted, and the ''uncanny valley'' effect emerges. Subtle motion (Low 2–3) reads as natural life rather than AI animation.',
   1),
  (v_quiz_id,
   'In Lightroom''s HDR Merge, what does the Deghost Amount setting control?',
   'multiple_choice',
   '["How much dynamic range the merged file retains","How the AI detects and corrects moving elements (people, foliage) between bracketed exposures","The level of sharpening applied to the merged file","The number of exposures used in the merge"]',
   'How the AI detects and corrects moving elements (people, foliage) between bracketed exposures',
   'Deghosting corrects the ''ghosting'' artefact caused by subject movement between bracketed exposures. Without it, a person walking through the frame during bracketing would appear as a semi-transparent double image in the merged HDR.',
   2),
  (v_quiz_id,
   'Which print export setting in Lightroom correctly prepares an image for a professional print lab that accepts TIFF?',
   'multiple_choice',
   '["JPEG, Quality 80, sRGB","TIFF, 8-bit, AdobeRGB","TIFF, 16-bit, with the lab''s ICC profile or sRGB","PNG, maximum quality, no colour profile"]',
   'TIFF, 16-bit, with the lab''s ICC profile or sRGB',
   'TIFF-16bit preserves maximum tonal information and avoids JPEG compression artefacts. Using the lab''s ICC profile (or sRGB if none is provided) ensures the colours the lab reproduces match what you saw on screen.',
   3),
  (v_quiz_id,
   'What is the recommended approach to atmospheric haze in drone aerial photography?',
   'multiple_choice',
   '["Apply maximum Dehaze to make the image as sharp as possible at distance","Apply 20–40% Dehaze to reduce haze while retaining natural-looking horizon depth","Add Clarity and Texture instead of Dehaze for cleaner results","Do not correct haze — it is a natural atmospheric condition that should be preserved"]',
   'Apply 20–40% Dehaze to reduce haze while retaining natural-looking horizon depth',
   'Moderate Dehaze (20–40%) restores colour and contrast at distance without making the horizon look artificially sharp. Over-dehazing makes distant elements appear closer than they physically are, breaking the image''s sense of depth and scale.',
   4),
  (v_quiz_id,
   'After applying Photoshop Generative Fill to extend a canvas, you plan to print the image at A1 size. What should you check before sending to the print lab?',
   'multiple_choice',
   '["That the file is saved as JPEG","That the generated area has no pixel-level artefacts visible at 200% zoom","That the Generative Layer is flattened to the background","That the image is converted to CMYK colour mode"]',
   'That the generated area has no pixel-level artefacts visible at 200% zoom',
   'AI-generated fill regions can contain subtle tonal inconsistencies or compression artefacts that are invisible at normal screen zoom but become visible at large print magnification. Checking at 200% and applying mild blur if needed prevents surprises at the print lab.',
   5);

  RAISE NOTICE '✓ Module 9 (Advanced Tools) content loaded.';
END $$;
