-- ============================================================
-- Module 5 Content: AI Portrait Retouching — Natural Results at Speed
-- ============================================================
DO $$
DECLARE
  v_course_id uuid; v_mod_id uuid;
  v_l1 uuid; v_l2 uuid; v_l3 uuid; v_l4 uuid; v_l5 uuid; v_l6 uuid; v_lq uuid;
  v_quiz_id uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ai-photography-practical-course';
  SELECT id INTO v_mod_id FROM modules WHERE course_id = v_course_id AND position = 5;
  SELECT id INTO v_l1 FROM lessons WHERE module_id = v_mod_id AND position = 1;
  SELECT id INTO v_l2 FROM lessons WHERE module_id = v_mod_id AND position = 2;
  SELECT id INTO v_l3 FROM lessons WHERE module_id = v_mod_id AND position = 3;
  SELECT id INTO v_l4 FROM lessons WHERE module_id = v_mod_id AND position = 4;
  SELECT id INTO v_l5 FROM lessons WHERE module_id = v_mod_id AND position = 5;
  SELECT id INTO v_l6 FROM lessons WHERE module_id = v_mod_id AND position = 6;
  SELECT id INTO v_lq FROM lessons WHERE module_id = v_mod_id AND position = 7;
  DELETE FROM content_blocks WHERE lesson_id IN (v_l1,v_l2,v_l3,v_l4,v_l5,v_l6,v_lq);

  -- ── L5.1: Natural vs over-retouched ──────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l1, 'text', 1, '{"html": "<h2>The Client Expectation Spectrum</h2><p>Portrait retouching is the most client-subjective part of photography post-production. Two clients with identical portraits will have completely different ideas of what a good retouch looks like. One wants light, natural enhancement that preserves their character. Another expects the Instagram-level smoothing they see on influencer feeds. A corporate client needs professional polish without any appearance of vanity retouching.</p><p>Before you retouch a single image, understand where your client sits on this spectrum. The problem with AI retouching tools is not that they over-retouch by default — most modern tools are well-calibrated. The problem is that photographers apply them without thinking about the specific client and shoot context.</p><p>Over-retouching has become more noticeable as viewers become AI-literate. Clients are increasingly unhappy with portraits that look processed — they may not be able to articulate why, but they know something is off. Natural retouching that preserves skin texture, real eye detail, and genuine skin tone is almost universally preferred when done correctly.</p>"}'),
  (v_l1, 'comparison_table', 2, '{"title": "Retouching Level by Client Type", "headers": ["Client Type", "Expected Level", "Key Priorities", "What to Avoid"], "rows": [["Corporate headshots", "Moderate — professional polish", "Blemish removal, even skin tone, flyaway hair", "Heavy smoothing, obvious plastic skin"], ["Wedding portraits", "Light to moderate", "Natural glow, even tone, remove temporary blemishes", "Heavy manipulation of features, artificial smoothing"], ["Maternity portraits", "Very light", "Natural, soft, organic", "Heavy digital alteration — authenticity is the point"], ["Fashion/editorial", "Heavy as directed", "Creative look, may include heavy stylisation", "Inconsistency — follow the brief"], ["Family portraits", "Light", "Sharp eyes, even tones, remove transient blemishes", "Heavy smoothing that makes subjects look unlike themselves"], ["E-commerce (people)", "Moderate", "Consistent, clean, natural", "Distracting retouching that draws attention to itself"]]}'),
  (v_l1, 'callout', 3, '{"variant": "important", "title": "Ask Before You Retouch", "body": "Add a retouching preference question to your client intake form: Do you prefer (a) light, natural retouching that preserves your features, (b) standard professional retouching, or (c) heavy retouching? One question prevents the most common post-delivery disappointment in portrait photography."}'),
  (v_l1, 'key_takeaway', 4, '{"title": "The Retouching Mindset", "points": ["Retouching should make clients look like the best version of themselves — not a different person.", "Over-retouching is increasingly noticed and commented on by clients. Natural results are preferred across most client types.", "Ask retouching preferences before the shoot, not after delivery.", "AI retouching tools are calibrated to produce natural results by default — do not push them to maximum strength without specific client context.", "Consistent retouching across a gallery matters as much as the quality on any single image."]}');

  -- ── L5.2: Luminar Neo Portrait AI ────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l2, 'tool_spotlight', 1, '{"name": "Luminar Neo", "description": "An AI-powered photo editor with dedicated portrait retouching tools: Skin AI (natural smoothing with texture preservation), Structure AI (enhances portrait detail without destroying texture), Face AI (eyes, lips, face shape), Sky AI (one-click sky replacement with realistic relighting), and Portrait Bokeh AI (background blur simulation). Works standalone or as a Lightroom / Photoshop plugin.", "url": "https://skylum.com/luminar-neo", "icon_url": ""}'),
  (v_l2, 'steps', 2, '{"title": "Luminar Neo Portrait Retouching Workflow", "steps": [{"title": "Open in Luminar Neo", "body": "Open your portrait directly in Luminar Neo, or use it as a Lightroom plugin (right-click image > Edit in > Luminar Neo). The plugin round-trip preserves your Lightroom edits and returns a TIFF to your catalog when done."}, {"title": "Skin AI — Natural Smoothing", "body": "In the Portrait category on the right panel, open Skin AI. Set Amount to 40-60 (start conservative). The tool smooths while preserving micro-texture — visible skin pores and fine texture should remain. Increase only if the client type warrants it. Check at 100% zoom."}, {"title": "Structure AI — Portrait Sharpening", "body": "Open Structure AI. Set Body to 20-30 to add subtle clarity to clothing and hair. Set Face to 0 — applying Structure to faces increases pores and wrinkles, which works against the smoothing you just applied."}, {"title": "Face AI — Eyes and Lips", "body": "Open Face AI. Sharpen Eyes: 30-50 (eyes should always be the sharpest element in a portrait). Face Light: adds a subtle catchlight fill, use at 10-20. For beauty or fashion work, explore Lips and Face Shape, but use extreme restraint on the latter."}, {"title": "Relight (optional)", "body": "If the lighting is uneven or flat, use the AI Scene Relighting or Portrait Bokeh AI to add warmth or separate the subject from the background. Portrait Bokeh AI simulates lens blur on the background — useful when a clean background separation was not achieved in camera."}]}'),
  (v_l2, 'callout', 3, '{"variant": "warning", "title": "Face Shape — Handle With Extreme Care", "body": "Luminar Face AI includes face slimming and reshaping controls. These are powerful and can produce obviously unnatural results very quickly. If you use these features at all, use them at under 10% strength and only with explicit client permission. The risk of client upset and reputational damage is real."}'),
  (v_l2, 'checklist', 4, '{"title": "Portrait Retouching Quality Check", "items": ["Skin texture is still visible at 100% zoom — not smooth like plastic or wax", "Eyes are the sharpest element in the frame", "Skin tone is even across the face without colour banding or patches", "Temporary blemishes removed, permanent features preserved", "Both sides of the face have consistent retouching treatment", "Gallery consistency: all portraits from the same session look like they were retouched by the same hand"]}');

  -- ── L5.3: Lightroom AI masking for portraits ─────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l3, 'text', 1, '{"html": "<h2>Lightroom AI Masking for Portrait Adjustments</h2><p>Lightroom AI Masking — introduced in 2022 and substantially improved since — allows precise, automatic selection of portrait-specific areas: the face, eyes, lips, teeth, skin, and hair. Each can be adjusted independently with Lightroom''s full adjustment toolkit. This is powerful for portrait work that stays entirely within Lightroom without requiring a round-trip to Luminar or Photoshop.</p>"}'),
  (v_l3, 'steps', 2, '{"title": "Lightroom Portrait Masking Workflow", "steps": [{"title": "Access Masking Panel", "body": "In the Develop module, click the Masking icon (circle with dotted border, above the Histogram panel) or press Shift+W. The masking panel opens."}, {"title": "Select Person — Skin", "body": "Click Add New Mask > Person. Lightroom detects all people in the frame. Check Person Mask Options and enable: Skin. Click Create. A mask is created covering just the skin. Apply smoothing adjustments: reduce Texture by -10 to -20, add slight clarity reduction (-5 to -10), add a touch of warmth."}, {"title": "Select Person — Eyes", "body": "Create a new mask > Person > Eyes. This selects the iris and eye whites separately. For eyes: add Texture +30-50, Clarity +10-20. Eyes should always be the sharpest, highest-contrast element."}, {"title": "Select Person — Hair", "body": "Create a new mask > Person > Hair. Useful for: adding slight sharpness to hair (Clarity +10-15), or adjusting hair colour/tone independently from skin."}, {"title": "Adjust Background Separately", "body": "Create a mask > Person > Invert. This selects everything except the person. You can now darken, soften, or blur the background tone independently from the subject. This simulates the separation you might achieve with a wider aperture."}]}'),
  (v_l3, 'expert_note', 3, '{"title": "How Lightroom Portrait Masking Uses AI", "body": "Lightroom''s Person masking is built on the same semantic segmentation foundation as background removal tools. The model classifies every pixel in the image and assigns it to semantic categories: face, skin, hair, clothing, background.\n\nThe quality of these masks has improved dramatically with each Lightroom update. Current (2025) masks are generally production-quality for most portrait work without manual refinement.\n\nEdge cases where masks need refinement: very dark skin against a dark background (separation is harder), curly or afro hair (complex edge profiles), multiple people overlapping, unusual clothing colours that match skin tone.\n\nFor these cases: click the mask thumbnail and use the brush to paint corrections on the mask. The underlying AI mask is non-destructive — you can always revert to the original AI mask if your manual refinement makes things worse."}'),
  (v_l3, 'callout', 4, '{"variant": "tip", "title": "Sync Masks Across a Portrait Session", "body": "Once you have built a set of portrait masks and adjustments on one image, use Copy/Paste or Sync in Lightroom to apply the same masks to other portraits from the same session (similar lighting and exposure). AI re-detects the subject in each image automatically — the adjustment values apply immediately. One setup, consistent results across the gallery."}');

  -- ── L5.4: Frequency separation deep dive ─────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l4, 'text', 1, '{"html": "<h2>Frequency Separation: What AI Retouching Does at the Pixel Level</h2><p>Every professional retouching tool — including the AI tools you are using — operates on a principle called frequency separation. Understanding this principle makes you a better operator: you will know when to push the tools harder and when to hold back, and you will be able to troubleshoot results that look wrong.</p><p>In photography, an image contains information at different scales (frequencies). <strong>Low frequencies</strong> are the broad tonal areas — the gradient of light across a face, the overall colour of skin. <strong>High frequencies</strong> are the fine details — skin pores, hair strands, eyelash definition, fabric texture.</p><p>Good retouching modifies the low frequency (even out skin tone, reduce shadows under eyes) without destroying the high frequency (preserve pore texture, fine hair detail, fabric weave). AI retouching tools do this separation automatically — this is why they can smooth skin without creating plastic results when used at appropriate strength levels.</p>"}'),
  (v_l4, 'expert_note', 2, '{"title": "Frequency Separation in Traditional vs AI Retouching", "body": "In Photoshop, frequency separation is done manually:\n1. Duplicate the layer twice.\n2. Apply a Gaussian Blur to the low-frequency layer (radius 4-8px for most portraits).\n3. Use Apply Image on the high-frequency layer to subtract the blur and leave only the texture.\n4. Edit the low-frequency layer only for tone corrections — this cannot affect texture.\n5. Edit the high-frequency layer only for texture corrections — this cannot affect tone.\n\nThis workflow is powerful but takes 5-15 minutes per image with skill.\n\nAI retouching tools (Luminar Skin AI, Lightroom AI masking with Texture reduction) do the same separation automatically within the model. The neural network learned to identify and separate these frequency bands from training on thousands of retouched vs unretouched portrait pairs.\n\nThe practical result: Luminar Skin AI at 50% is approximately equivalent to careful manual frequency separation retouching — but takes 2 seconds instead of 10 minutes.\n\nThe limitation: AI cannot make context-specific decisions the way a human retoucher can. It treats all skin identically. For high-end beauty work or editorial retouching with specific brief requirements, traditional frequency separation still has a place."}'),
  (v_l4, 'key_takeaway', 4, '{"title": "Frequency Separation — Key Concepts", "points": ["Every AI skin retouching tool separates low-frequency (tone) from high-frequency (texture) automatically.", "Skin smoothing reduces low-frequency irregularities without touching texture. This is why good AI retouching looks natural.", "Over-retouching at high AI strength values also removes high-frequency detail — producing the plastic, textureless look.", "For beginners: use AI tools at 40-60% strength for natural results. Increase only for specific beauty briefs.", "For advanced users: understanding frequency separation helps you identify exactly which type of retouching is needed for each problem area."]}');

  -- ── L5.5: Ethics of reshaping ─────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l5, 'text', 1, '{"html": "<h2>The Ethics of Face and Body Reshaping Tools</h2><p>AI portrait tools include features that go beyond retouching into reshaping: face slimming, face width adjustment, nose reshaping, lip enlargement, eye enlargement, body slimming. These tools are technically accessible to any photographer with a Luminar Neo or Facetune subscription. The ethical question is whether and when you should use them.</p><p>This lesson does not tell you what to do. It gives you the framework to make informed decisions and to communicate clearly with clients about what you have done to their images.</p>"}'),
  (v_l5, 'callout', 2, '{"variant": "danger", "title": "The Key Ethical Risk", "body": "Reshaping tools alter a person''s physical appearance in ways that were not true at the time of the photograph. Delivering reshaped images without disclosure means the client does not know their own appearance has been digitally altered. This becomes problematic when: (1) the client shares the image publicly as a representation of how they look, (2) others compare the image to the real person, (3) the client uses the image in a professional context where accurate representation matters."}'),
  (v_l5, 'text', 3, '{"html": "<h3>A Framework for Responsible Practice</h3><p><strong>Blemish and temporary correction</strong>: Always acceptable without disclosure. Removing a pimple, reducing redness, lightening under-eye circles — these are temporary conditions, not permanent features.</p><p><strong>Tone and colour correction</strong>: Always acceptable. Even skin tone, correct colour casts, reduce shadows — these are technical corrections, not alterations of appearance.</p><p><strong>Feature reshaping</strong>: Requires explicit client consent. If a client has not asked for it, do not do it. If a client asks for it, confirm in writing what changes they want and that they understand the result will not represent their actual physical appearance in the delivered images.</p><p><strong>AI-generated features</strong>: In some cases (generative AI eyes, teeth, etc.) you are effectively replacing real physical features with AI-generated ones. This is advanced territory that requires clear disclosure and client understanding.</p>"}'),
  (v_l5, 'ai_prompt', 4, '{"label": "Draft a Retouching Policy", "tool": "ChatGPT", "prompt": "I am a portrait photographer in Zambia. Help me write a clear, professional retouching policy statement for my client intake form. It should cover:\n1. What I include in standard retouching (blemish removal, skin tone evening, eye enhancement)\n2. What I do NOT do without explicit request (face/body reshaping, skin colour alteration)\n3. A section where clients can request additional retouching and indicate their preference level (light, standard, heavy)\n4. A statement that heavy retouching is available for an additional fee and with signed consent\n\nTone: professional, friendly, not defensive. Length: one page maximum. Format: numbered sections with a client checkbox consent at the bottom."}'),
  (v_l5, 'key_takeaway', 5, '{"title": "Ethical Retouching Principles", "points": ["Temporary corrections (blemishes, redness, shadows): always acceptable, no disclosure needed.", "Tone and colour corrections: always acceptable, these are technical not appearance alterations.", "Feature reshaping (face, body shape): requires explicit client consent — add it to your intake form.", "Never reshape features that a client did not request. The risk to your reputation is not worth the perceived improvement.", "Deliver what the client asked for, not what you think they should want. Your job is service, not transformation."]}');

  -- ── L5.6: Reusable retouching profiles ──────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l6, 'text', 1, '{"html": "<h2>Creating Reusable Portrait Retouching Profiles</h2><p>The biggest time sink in portrait retouching is not the retouching itself — it is reconfiguring every tool from scratch for every session. A reusable retouching profile is a saved set of adjustments you apply in one click as a starting point for a portrait session. You then make small per-image refinements, but the heavy lifting is done.</p>"}'),
  (v_l6, 'steps', 2, '{"title": "Building Your Retouching Profile System", "steps": [{"title": "Define Your Client Tiers", "body": "Identify your main client types: Corporate, Wedding, Family, Beauty/Fashion. Each needs a different default retouching level. You will build one Lightroom preset and one Luminar Neo profile per tier."}, {"title": "Build the Lightroom Preset", "body": "Start with a well-retouched portrait from each tier. Create your AI mask adjustments (skin, eyes, hair). Once satisfied, go to the Presets panel, click the + icon, and Save Current Settings as Preset. Include: AI masks, any tone adjustments, sharpening settings. Name clearly: Corporate Portrait Base, Wedding Portrait Base."}, {"title": "Build the Luminar Neo Preset", "body": "In Luminar Neo, set your Skin AI, Structure AI, Face AI, and Portrait Bokeh values for a representative portrait from the tier. Save as a Luminar preset (Presets menu > Save Preset). Name it to match your Lightroom tier name for clarity."}, {"title": "Document Your Settings", "body": "Write down the exact values for each setting in each profile. If Luminar Neo updates and resets your presets, you can rebuild immediately. Keep a simple table in your phone notes or a shared document."}, {"title": "Apply and Refine", "body": "For every new portrait session: apply the tier preset immediately. Then only make per-image adjustments for images that need it (typically 10-20% of portraits need individual attention beyond the preset). The other 80-90% are done after the first click."}]}'),
  (v_l6, 'case_study', 3, '{"title": "Headshot Photographer — 40 Corporate Portraits in One Session", "context": "A Lusaka corporate headshot photographer was spending 3-4 minutes per portrait in retouching — 2.5 hours for a 40-person session. They had no consistent process, rebuilding adjustments for each image.", "action": "Built a Corporate Portrait Base preset in Lightroom (AI skin mask at Texture -15, AI eyes mask at Texture +40 Clarity +15) and a matching Luminar Neo preset (Skin AI 45, Structure AI Body 25 Face 0, Face AI Eyes Sharpen 40). Tested on a sample session and refined the values.", "result": "Standard preset application time: 15 seconds per image. Per-image refinement needed on 8 of 40 images (20%): average 90 seconds each. Total retouching time: 10 minutes (preset) + 12 minutes (refinements) = 22 minutes for 40 portraits. Reduction from 2.5 hours to 22 minutes — an 85% time saving with more consistent results."}'),
  (v_l6, 'checklist', 4, '{"title": "Retouching Profile Setup Checklist", "items": ["Defined 2-3 client tiers with different retouching levels", "Built a Lightroom preset for each tier (AI masks + adjustments)", "Built a matching Luminar Neo preset for each tier if using Luminar", "Tested each preset on at least 10 real portraits and refined values", "Documented exact settings in case presets need to be rebuilt", "Established naming convention: consistent names across Lightroom and Luminar presets"]}');

  -- ── Module 5 Checkpoint Quiz ──────────────────────────────────────────
  DELETE FROM quizzes WHERE lesson_id = v_lq;
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES (v_lq, 'quiz', 1, '{"quiz_id": ""}');
  INSERT INTO quizzes (lesson_id, title, pass_threshold, max_attempts)
    VALUES (v_lq, 'Module 5: AI Portrait Retouching', 70, 3) RETURNING id INTO v_quiz_id;
  UPDATE content_blocks SET content = jsonb_build_object('quiz_id', v_quiz_id::text)
    WHERE lesson_id = v_lq AND type = 'quiz';

  INSERT INTO quiz_questions (quiz_id, question, options, correct_indices, explanation, position) VALUES
    (v_quiz_id, 'A photographer receives a corporate headshot portrait from a new client. They have not discussed retouching preferences. What is the appropriate default approach?',
     '["Apply maximum smoothing — corporate clients always want heavy retouching", "Apply light, natural retouching that removes temporary blemishes and evens skin tone, preserving natural texture", "Apply no retouching — let the client request it if they want it", "Apply reshaping tools to slim the face and brighten the eyes significantly"]',
     '{1}', 'Without explicit client preferences, light natural retouching is the professional default. It removes genuine distractions (blemishes, shadows) without altering permanent features.', 1),
    (v_quiz_id, 'What is frequency separation in portrait retouching?',
     '["Separating the retouching work into frequency-based sessions (one per week)", "Separating an image into its low-frequency tonal information and high-frequency texture, allowing each to be edited independently", "Reducing the noise frequency in portrait images using Topaz", "A Photoshop blending mode used for colour retouching"]',
     '{1}', 'Frequency separation divides an image into broad tonal areas (low frequency) and fine detail/texture (high frequency). Good retouching edits the low frequency to smooth tones without touching the high frequency texture.', 2),
    (v_quiz_id, 'Setting Luminar Neo Skin AI to 90% strength on a portrait of a wedding client. What is the likely result?',
     '["An excellent result — maximum smoothing is always best for wedding portraits", "Plastic-looking skin with no visible texture — an unnatural result that most clients dislike", "The image will be rejected by Luminar as over-processed", "This is correct for outdoor wedding portraits where wind causes skin imperfections"]',
     '{1}', 'Very high strength values remove high-frequency skin texture along with tonal irregularities, producing the plastic/wax-like look that clients increasingly identify and dislike.', 3),
    (v_quiz_id, 'A photographer wants to adjust the brightness of just the skin in a portrait without affecting hair or clothing. Which Lightroom feature handles this?',
     '["The HSL panel — adjusting the Orange hue slider", "AI Masking > Person > Skin — creates an automatic selection of just the skin areas", "The Basic panel Exposure slider", "The Radial Filter positioned over the face"]',
     '{1}', 'Lightroom AI Masking > Person > Skin creates a precise automatic selection of skin pixels. Adjustments made to this mask affect only the selected skin areas.', 4),
    (v_quiz_id, 'Face and body reshaping features in AI tools should be used:',
     '["Routinely on all portrait clients — clients always appreciate looking slimmer", "Only with explicit client consent, clearly communicated before delivery", "Never — these features violate photography ethics regardless of client preference", "Only on social media images, not on print deliverables"]',
     '{1}', 'Reshaping alters a client''s physical appearance as represented in the photograph. This requires informed consent. Clients who want reshaping should request it; photographers should not apply it without being asked.', 5);

  RAISE NOTICE '✓ Module 5 content loaded (6 lessons + quiz).';
END $$;
