-- ============================================================
-- Module 3 Content: Smart Culling — Select the Best Shots Fast
-- ============================================================
DO $$
DECLARE
  v_course_id uuid; v_mod_id uuid;
  v_l1 uuid; v_l2 uuid; v_l3 uuid; v_l4 uuid; v_l5 uuid; v_lq uuid;
  v_quiz_id uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ai-photography-practical-course';
  SELECT id INTO v_mod_id FROM modules WHERE course_id = v_course_id AND position = 3;
  SELECT id INTO v_l1 FROM lessons WHERE module_id = v_mod_id AND position = 1;
  SELECT id INTO v_l2 FROM lessons WHERE module_id = v_mod_id AND position = 2;
  SELECT id INTO v_l3 FROM lessons WHERE module_id = v_mod_id AND position = 3;
  SELECT id INTO v_l4 FROM lessons WHERE module_id = v_mod_id AND position = 4;
  SELECT id INTO v_l5 FROM lessons WHERE module_id = v_mod_id AND position = 5;
  SELECT id INTO v_lq FROM lessons WHERE module_id = v_mod_id AND position = 6;
  DELETE FROM content_blocks WHERE lesson_id IN (v_l1,v_l2,v_l3,v_l4,v_l5,v_lq);

  -- ── L3.1: Economics of culling ────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l1, 'text', 1, '{"html": "<h2>The Hidden Cost of Manual Culling</h2><p>Culling is the act of reviewing every image from a shoot and deciding which to keep and which to discard. It is the first stage of post-production and, for most photographers, the one that consumes the most unbillable time.</p><p>Consider a typical wedding photographer. A 10-hour wedding produces 1,500-2,500 raw frames. Reviewing each one at even 5 seconds per image takes over 2 hours. Reviewing properly — comparing similar shots to pick the sharpest, checking eyes, assessing composition — easily takes 3-4 hours. That is 3-4 hours of work that produces zero deliverable images.</p><p>AI culling tools do not make the final creative decision for you. They handle the mechanical first pass: eliminating obvious technical failures (blurry, blinked, severely underexposed) and grouping burst sequences so you choose one from each group rather than reviewing 10. The result is a shortlist of genuinely viable images — and your review time drops from hours to minutes.</p>"}'),
  (v_l1, 'ai_prompt', 2, '{"label": "Calculate Your Culling Cost", "tool": "ChatGPT", "prompt": "I am a photographer. Help me calculate the true cost of manual culling in my business.\n\nMy numbers:\n- Average shoot size: [X] images\n- Average culling time per shoot: [Y] hours\n- Number of shoots per month: [Z]\n- My target hourly rate: ZMW [rate] per hour\n\nPlease calculate:\n1. Total monthly hours spent culling\n2. Monthly cost of culling at my hourly rate\n3. Annual cost\n4. If AI culling reduced my time by 80%, how many hours and how much money would I recover per year?\n5. At what monthly subscription price would an AI culling tool pay for itself in the first month?"}'),
  (v_l1, 'comparison_table', 3, '{"title": "Culling Time: Manual vs AI-Assisted", "headers": ["Shoot Type", "Images Shot", "Manual Culling Time", "AI-Assisted Time", "Saving"], "rows": [["Corporate headshots", "80-120 images", "45-60 minutes", "8-12 minutes", "80%"], ["Family portrait session", "150-250 images", "60-90 minutes", "10-18 minutes", "82%"], ["Wedding reception", "400-600 images", "2.5-4 hours", "25-40 minutes", "84%"], ["Full-day wedding", "1,200-2,000 images", "5-8 hours", "45-75 minutes", "87%"], ["Commercial product shoot", "100-200 images", "30-45 minutes", "6-10 minutes", "80%"]]}'),
  (v_l1, 'key_takeaway', 4, '{"title": "The Economics of Culling", "points": ["Culling is the largest single time cost in post-production for most photographers — yet it adds zero creative value to the final gallery.", "At ZMW 150/hour opportunity cost, 4 hours of wedding culling costs ZMW 600 of time value per shoot.", "AI culling targets an 80-90% time reduction on the mechanical first pass. Your creative selection of the final set still happens — just from a much shorter shortlist.", "The financial case is straightforward: if AI saves 3 hours per shoot and you do 8 shoots per month, you recover 24 hours of time monthly.", "Use the recovered time to take on more shoots, improve marketing, or rest — all of which improve your business more than additional culling hours."]}');

  -- ── L3.2: AfterShoot setup ────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l2, 'tool_spotlight', 1, '{"name": "AfterShoot", "description": "The leading dedicated AI culling application for photographers. Runs locally on your Mac or Windows computer — no cloud upload required. Analyses each image for sharpness, exposure, blink detection, and groups burst sequences. Integrates with Lightroom, Capture One, and other DAM tools via XMP metadata or direct folder import.", "url": "https://aftershoot.com", "icon_url": ""}'),
  (v_l2, 'steps', 2, '{"title": "AfterShoot Setup and First Cull", "steps": [{"title": "Download and Install", "body": "Go to aftershoot.com and download the installer for your operating system (Mac or Windows). Install and launch. You will need to create an account and start a subscription (there is no meaningful free tier for professional use)."}, {"title": "Import Your Shoot", "body": "Click New Album. Navigate to your shoot folder — either your original RAW files or your exported folder. AfterShoot reads directly from the original location without copying files. Select all images and confirm the import."}, {"title": "Configure Your Culling Criteria", "body": "Before processing, set your criteria: Minimum Sharpness (recommended: 60-70 for most work, 50 for fast action), Burst Grouping (On, with sensitivity Medium), Face Detection (On if portrait work), Closed Eyes Detection (On for portraits). Save these as a preset for future reuse."}, {"title": "Run the AI Analysis", "body": "Click Start Culling. AfterShoot processes each image locally — no upload required. Time varies by computer speed: typically 2-5 minutes for 500 images on a modern laptop. Progress bar shows status."}, {"title": "Review the Shortlist", "body": "AfterShoot presents a Three-Star shortlist and a Reject pile. Review the shortlist in its built-in browser: use arrow keys to navigate, star rating to keep (5 stars), and X to reject. You are reviewing a curated list, not every frame."}, {"title": "Export Selections to Lightroom", "body": "Once satisfied with your selections, click Export to Lightroom (or the relevant export option). AfterShoot writes your ratings as XMP star data that Lightroom reads directly. Filter your Lightroom catalog by 5 stars to see only your keepers."}]}'),
  (v_l2, 'callout', 3, '{"variant": "tip", "title": "Build Your Preset Library by Shoot Type", "body": "Wedding ceremony culling needs different settings than corporate headshots. Save a named preset for each shoot type you regularly do: Wedding Ceremony (strict sharpness, blink detection on), Portraits (moderate sharpness, grouping sensitive), Sports/Events (lower sharpness threshold for action). Apply the right preset for each job without reconfiguring."}'),
  (v_l2, 'checklist', 4, '{"title": "After Your First AfterShoot Cull", "items": ["Reviewed every image in the shortlist (do not blindly trust AI stars)", "Checked the reject pile briefly for any images the AI may have incorrectly dismissed", "Compared AI selection time vs your estimate for manual culling", "Saved your culling criteria as a named preset for future use", "Exported ratings to Lightroom and verified they appear correctly"]}');

  -- ── L3.3: Lightroom AI ratings ────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l3, 'text', 1, '{"html": "<h2>Lightroom AI Ratings and Smart Previews</h2><p>If you are already a Lightroom user and do not want to add another application, Lightroom Classic includes AI-assisted features that improve culling speed. These are not as powerful as dedicated culling tools like AfterShoot, but they are fast, integrated, and free with your existing subscription.</p>"}'),
  (v_l3, 'steps', 2, '{"title": "Lightroom AI Culling Workflow", "steps": [{"title": "Import with Smart Previews", "body": "During import, enable Build Smart Previews. This creates a fast-rendering proxy for each image that Lightroom uses for display and some AI operations. It slightly increases import time but dramatically improves browsing and analysis speed afterward."}, {"title": "People View — AI Face Detection", "body": "After import, click the People icon (or press O) in the Library module. Lightroom uses AI to detect faces in all images and groups them by person. This is extremely useful for portraits and events — you can find all photos of a specific person instantly and compare expressions across the group."}, {"title": "AI Auto-Select in Grid View", "body": "In Grid view, select all images (Ctrl+A) and use Photo > Auto Advance to step through them quickly. Flag keepers with P (Pick) and rejects with X. This is not AI selection itself, but it uses Lightroom''s sorting and AI metadata to make your own selection faster."}, {"title": "Compare View for Final Selection", "body": "For burst sequences, select all similar shots and press C to enter Compare view. Navigate between candidates and pick the sharpest. This is where human judgement still dominates — AI can shortlist but cannot pick the one with the best expression."}, {"title": "Filter to Picks", "body": "Once done, use the Filter bar to show only Picked images. This is your working set for the rest of post-production."}]}'),
  (v_l3, 'comparison_table', 3, '{"title": "AfterShoot vs Lightroom AI Culling", "headers": ["Feature", "AfterShoot", "Lightroom AI"], "rows": [["Sharpness detection", "Precise AI scoring", "Basic — relies on your eye"], ["Burst grouping", "Automatic AI grouping", "Manual comparison in Compare view"], ["Blink detection", "Yes", "Basic via People view"], ["Cost", "Separate subscription", "Included in Lightroom plan"], ["Speed on large shoots", "Fastest — 2-5 min per 500 images", "Slower — depends on manual review pace"], ["Workflow integration", "Exports to Lightroom via XMP", "Native Lightroom — no export step"], ["Best for", "Wedding, event, sports photographers", "Portrait and controlled-environment photographers"]}'),
  (v_l3, 'expert_note', 4, '{"title": "How Lightroom Smart Previews Affect AI Performance", "body": "Smart Previews are compressed DNG proxy files stored at 2540px on the long edge (about 5MP). For AI operations like face detection and focus point analysis, Lightroom uses these proxies rather than the full RAW files, which is why analysis is faster than you might expect.\n\nThe implication: AI face detection and auto-analysis accuracy is slightly lower on Smart Previews than on full RAW files, but for culling purposes — where you are making rough keep/reject decisions — this accuracy level is more than adequate.\n\nFor final creative selection and quality-critical decisions, always view the full-resolution image (press 1:1 in the Develop module) before committing to a hero shot."}');

  -- ── L3.4: Culling criteria presets ───────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l4, 'text', 1, '{"html": "<h2>Building Culling Presets by Shoot Type</h2><p>The goal of a culling preset is to match the AI criteria to the standards of your specific shoot type. A wedding ceremony requires different standards than a corporate headshot session. Once built, a preset applies your standards in seconds — with no reconfiguration.</p>"}'),
  (v_l4, 'steps', 2, '{"title": "Recommended Presets by Shoot Type", "steps": [{"title": "Corporate Headshots Preset", "body": "Sharpness minimum: 75 (high — clients expect pin-sharp faces). Blink detection: On (critical — no closed eyes in a professional headshot). Burst grouping: On, sensitivity High (group similar poses tightly). Expression filter: On if available. Rationale: small image count, high quality bar per image."}, {"title": "Wedding Ceremony Preset", "body": "Sharpness minimum: 55 (lower — fast action, long lens, moving subjects mean some motion blur is expected). Blink detection: On (still important). Burst grouping: On, sensitivity Medium (group bursts but allow more variation). Expression filter: On. Rationale: high image count, selecting for emotional moments not just technical perfection."}, {"title": "Portrait Session Preset", "body": "Sharpness minimum: 65. Blink detection: On. Burst grouping: High sensitivity (portrait sessions often have 5-10 frames per pose; AI groups them and you pick the best expression). Rationale: controlled environment, moderate image count, primary selection criterion is expression and connection."}, {"title": "Events and Functions Preset", "body": "Sharpness minimum: 50. Blink detection: On. Burst grouping: Low sensitivity (events are chaotic; preserve more unique moments). Rationale: high image count with diverse subjects, prioritise coverage over technical perfection."}]}'),
  (v_l4, 'case_study', 3, '{"title": "Wedding Photographer — 1,800 Images to Delivery", "context": "A Lusaka wedding photographer was spending 6-7 hours culling a full-day wedding (1,800 frames) before any editing could begin. This meant galleries were delivered 3-4 weeks after the wedding date, causing client tension.", "action": "Set up AfterShoot with a dedicated Wedding ceremony preset (sharpness 55, blink detection on, burst grouping medium). First run on a 1,800-image wedding: AfterShoot produced a 380-image shortlist in 18 minutes. Photographer reviewed shortlist in 35 minutes, selected 320 final keepers. Total culling time: 53 minutes.", "result": "Culling time dropped from 6.5 hours to under 1 hour — an 85% reduction. Gallery delivery improved from 3-4 weeks to 10-14 days. Client satisfaction scores improved. The photographer took on two additional shoots per month with the recovered time."}'),
  (v_l4, 'checklist', 4, '{"title": "Your Preset Setup Checklist", "items": ["Created a dedicated preset for each shoot type I regularly do", "Tested each preset on a real shoot from my archive", "Compared AI shortlist quality against my expected selection", "Adjusted sharpness threshold based on test results", "Named presets clearly (not Preset 1 — use Wedding Ceremony, Corporate Headshots, etc.)", "Documented which preset to use for which client type"]}');

  -- ── L3.5: Same-day delivery workflow ─────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l5, 'expert_note', 1, '{"title": "Advanced: Building a Same-Day Delivery Workflow", "body": "Same-day or next-day delivery has become a premium offering in competitive photography markets. AI culling is the foundation that makes it possible. Here is the complete workflow framework:\n\n1. ON LOCATION: Tether to a laptop or periodically transfer cards. Run AfterShoot on each card batch while shooting. By the time the event ends, half your culling is done.\n\n2. IN TRANSIT OR AT HOME: Open AfterShoot results. Do your selection review. If you use Lightroom auto-sync, your edits begin applying as you select.\n\n3. BATCH EDITING: Apply your preset immediately to all keepers. Use AI auto-grade on any images with significant exposure variation. For portraits, run Luminar Neo Portrait AI on the final hero images.\n\n4. SMART EXPORT: Use Lightroom export presets configured for your delivery platform. Upload to Pic-Time, Narrative, or Pixieset. Set client notification to go automatically on upload completion.\n\nWith this workflow, a corporate event shooting from 6pm to 10pm can have a gallery live by midnight — a premium differentiator that most photographers cannot offer at all."}'),
  (v_l5, 'steps', 2, '{"title": "Same-Day Delivery — The System", "steps": [{"title": "Prepare the Night Before", "body": "Format memory cards, charge batteries, configure AfterShoot with the correct preset for the next day''s shoot type. Set up your export preset in Lightroom. Confirm the delivery platform is ready."}, {"title": "First Card Transfer (During Event)", "body": "After the first hour of shooting, transfer the first card. Run AfterShoot immediately. It processes in the background while you shoot. Do not wait until the end."}, {"title": "Post-Event Rapid Cull", "body": "At the event end, transfer remaining cards. AfterShoot processes. Do your human shortlist review — target 30-45 minutes maximum. Export picks to Lightroom."}, {"title": "Speed Grade", "body": "Apply your signature preset. Run Auto on any problem images. Sync adjustments. Do not over-edit on same-day work — clients value speed and natural results, not heavy processing."}, {"title": "Export and Deliver", "body": "Export at web resolution (longest edge 2000-2500px for gallery platforms). Upload. Send the delivery link."}]}'),
  (v_l5, 'key_takeaway', 3, '{"title": "Same-Day Delivery — The Business Case", "points": ["Same-day delivery commands a 30-50% price premium in most markets. Charge accordingly.", "AI culling is the prerequisite — without it, the timeline is physically impossible for large shoots.", "You do not need to do same-day delivery for every client. Offer it as a premium tier on your pricing structure.", "First attempt: do same-day delivery on a shoot you already have scheduled. Test your workflow before committing it to a client expectation.", "The system gets faster with every use. The first time takes effort to set up. The tenth time is muscle memory."]}');

  -- ── Module 3 Checkpoint Quiz ───────────────────────────────────────────
  DELETE FROM quizzes WHERE lesson_id = v_lq;
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES (v_lq, 'quiz', 1, '{"quiz_id": ""}');
  INSERT INTO quizzes (lesson_id, title, pass_threshold, max_attempts)
    VALUES (v_lq, 'Module 3: Smart Culling', 70, 3) RETURNING id INTO v_quiz_id;
  UPDATE content_blocks SET content = jsonb_build_object('quiz_id', v_quiz_id::text)
    WHERE lesson_id = v_lq AND type = 'quiz';

  INSERT INTO quiz_questions (quiz_id, question, options, correct_indices, explanation, position) VALUES
    (v_quiz_id, 'What does AI culling primarily do in the photography workflow?',
     '["Makes all creative keep/reject decisions so the photographer does not have to", "Performs a mechanical first pass — removing obvious technical failures and grouping burst sequences — so the photographer reviews a shorter, higher-quality shortlist", "Automatically edits and colour grades selected images", "Replaces the need to sort images in Lightroom"]',
     '{1}', 'AI culling handles the mechanical work (blur, blinks, duplicates). The final creative selection still requires the photographer''s eye.', 1),
    (v_quiz_id, 'A portrait photographer should set AfterShoot''s sharpness minimum lower for a wedding ceremony than for studio headshots. Why?',
     '["Wedding photos are viewed at lower resolution so sharpness matters less", "Fast-moving subjects in dynamic lighting mean some motion softness is acceptable; being too strict would eliminate valid emotional moments", "Lightroom processes wedding RAWs differently than studio files", "AfterShoot performs better on JPEG exports from weddings than RAW files"]',
     '{1}', 'In dynamic environments (ceremony, dancing, children), some motion blur is unavoidable. Setting too strict a sharpness threshold eliminates genuine moments. A lower threshold keeps more viable frames for creative selection.', 2),
    (v_quiz_id, 'What is the main advantage of running AfterShoot locally rather than uploading to a cloud culling service?',
     '["Local processing is always faster than cloud", "Your client images remain on your own system — no privacy risk from uploading to third-party servers", "Local processing produces better AI quality results", "Cloud services do not support RAW files from professional cameras"]',
     '{1}', 'Privacy and client confidentiality are the primary reasons professional photographers prefer local AI processing. Wedding, portrait, and corporate images are sensitive and should not leave your controlled environment.', 3),
    (v_quiz_id, 'A photographer culls a 200-image portrait session manually in 75 minutes. AI culling reduces this to 12 minutes. They do 6 portrait sessions per month. How many hours do they recover monthly?',
     '["3.5 hours", "5.25 hours", "6.3 hours", "7.5 hours"]',
     '{2}', '(75 - 12) minutes saved = 63 minutes per session. 63 x 6 = 378 minutes = 6.3 hours per month.', 4),
    (v_quiz_id, 'What is Lightroom Smart Previews and why are they relevant to culling speed?',
     '["High-resolution versions of images stored in the cloud for fast access", "Compressed proxy files that Lightroom uses for display and AI operations — faster to process than full RAW files", "A feature that automatically picks the best photos from a shoot", "Colour-managed previews that show what a print will look like"]',
     '{1}', 'Smart Previews are lightweight proxy files (around 5MP) that Lightroom uses for display and AI operations instead of the full RAW file. This dramatically speeds up browsing and AI analysis.', 5);

  RAISE NOTICE '✓ Module 3 content loaded (5 lessons + quiz).';
END $$;
