-- ============================================================
-- Module 6 Content: AI Colour Grading at Scale
-- ============================================================
DO $$
DECLARE
  v_course_id uuid; v_mod_id uuid;
  v_l1 uuid; v_l2 uuid; v_l3 uuid; v_l4 uuid; v_l5 uuid; v_l6 uuid;
  v_lm uuid; v_lq uuid; v_quiz_id uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ai-photography-practical-course';
  SELECT id INTO v_mod_id FROM modules WHERE course_id = v_course_id AND position = 6;
  SELECT id INTO v_l1 FROM lessons WHERE module_id = v_mod_id AND position = 1;
  SELECT id INTO v_l2 FROM lessons WHERE module_id = v_mod_id AND position = 2;
  SELECT id INTO v_l3 FROM lessons WHERE module_id = v_mod_id AND position = 3;
  SELECT id INTO v_l4 FROM lessons WHERE module_id = v_mod_id AND position = 4;
  SELECT id INTO v_l5 FROM lessons WHERE module_id = v_mod_id AND position = 5;
  SELECT id INTO v_l6 FROM lessons WHERE module_id = v_mod_id AND position = 6;
  SELECT id INTO v_lm FROM lessons WHERE module_id = v_mod_id AND position = 7;
  SELECT id INTO v_lq FROM lessons WHERE module_id = v_mod_id AND position = 8;
  DELETE FROM content_blocks WHERE lesson_id IN (v_l1,v_l2,v_l3,v_l4,v_l5,v_l6,v_lm,v_lq);

  -- ── L6.1: Colour theory essentials ───────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l1, 'text', 1, '{"html": "<h2>Colour Theory Every Photographer Must Understand</h2><p>You do not need a fine arts degree to grade colour effectively. But you do need to understand the three axes that describe every colour adjustment you will make: <strong>Hue</strong> (what colour it is), <strong>Saturation</strong> (how much colour there is), and <strong>Luminance</strong> (how bright that colour is). Every slider in every colour grading tool maps to one or more of these three properties.</p><p>You also need to understand colour temperature and tint — the two-dimensional scale that describes the warmth or coolness of white light. Daylight at noon is around 5500K (neutral). Golden hour light is 3000-4000K (warm orange). Shade is 7000K+ (cool blue). When you set white balance, you are correcting for the colour temperature of the light source so that whites appear neutral. When you grade creatively, you are deliberately tilting away from neutral for emotional effect.</p>"}'),
  (v_l1, 'comparison_table', 2, '{"title": "Colour Temperature and Mood", "headers": ["Kelvin Range", "Light Quality", "Mood", "Common Source"], "rows": [["2000-3000K", "Warm orange-red", "Intimate, dramatic, golden", "Candles, tungsten bulbs, sunset"], ["3000-4000K", "Warm yellow", "Cosy, warm, inviting", "Early morning, late afternoon sun"], ["4500-5500K", "Neutral white", "Clean, professional, accurate", "Midday sun, flash, studio strobe"], ["6000-7500K", "Cool blue-white", "Airy, fresh, lifestyle", "Overcast sky, open shade"], ["8000K+", "Very cool blue", "Dramatic, cinematic, cold", "Deep shade, stormy sky"]]}'),
  (v_l1, 'expert_note', 3, '{"title": "Colour Spaces and Why They Matter for Photographers", "body": "A colour space defines the range of colours that can be represented in an image file. The three most relevant to photographers:\n\nsRGB: The standard for web, social media, and consumer printing. Every display can show sRGB colours. When in doubt, deliver in sRGB.\n\nAdobe RGB (1998): A wider colour space that can represent about 35% more colours than sRGB, particularly in the green-cyan range. Use for professional print work if your lab supports it. Note: images opened in a non-colour-managed application will look desaturated.\n\nProPhoto RGB: The widest standard colour space — used internally by Lightroom for processing. Delivering to clients in ProPhoto RGB is not advisable as most applications cannot display it correctly.\n\nFor AI colour grading tools: most AI models process images in a normalised internal colour space. The output respects your chosen colour space setting. Always set your Lightroom export colour space to match the delivery destination: sRGB for web/social, Adobe RGB if specified by print lab."}'),
  (v_l1, 'key_takeaway', 4, '{"title": "Colour Theory Essentials", "points": ["Every colour is described by three properties: Hue (what colour), Saturation (how much), Luminance (how bright).", "Colour temperature describes warmth or coolness. Warm tones (low Kelvin) feel intimate. Cool tones (high Kelvin) feel clean and airy.", "Your colour grade creates mood. Intentional grading is not correcting errors — it is making emotional decisions.", "For client delivery: sRGB for web and social, Adobe RGB if your print lab requires it.", "Consistent colour across a gallery is more important than any individual colour decision."]}');

  -- ── L6.2: Lightroom AI colour grading ────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l2, 'text', 1, '{"html": "<h2>Lightroom AI Colour Grading in Practice</h2><p>Lightroom''s AI Auto function analyses exposure, contrast, highlights, shadows, whites, blacks, and colour balance for each individual image and sets a starting-point adjustment based on its training data. The result is never a finished grade — but it is almost always a better starting point than a flat RAW file, and for volume work it saves significant time.</p><p>The real power in Lightroom for colour grading is the preset-and-sync workflow: apply your signature preset to the first image, make per-image adjustments where needed, then sync to the rest of the gallery. AI Auto handles the images that Auto adjustments are sufficient for, freeing you to spend time only on outliers.</p>"}'),
  (v_l2, 'steps', 2, '{"title": "AI-Assisted Colour Grading Workflow in Lightroom", "steps": [{"title": "Apply Your Signature Preset", "body": "Select all images from the session. Apply your signature Lightroom preset to all (right-click preset > Apply to Selected). This sets your creative baseline: your contrast curve, colour balance, and stylistic adjustments."}, {"title": "Sort by Exposure Deviation", "body": "Use the Library Grid view. Add a Smart Collection filter for images where exposure deviates significantly from the average (or sort by Exposure if you have capture data). Flag these for individual attention."}, {"title": "AI Auto on Flagged Images", "body": "For images with significant exposure deviation, open in Develop and click the Auto button (magic wand in the Basic panel). This adjusts exposure, contrast, highlights, shadows, whites, and blacks per-image. Your preset colours are preserved; only tonal adjustments are affected."}, {"title": "Sync Adjustments", "body": "Once satisfied with a batch, select all and Sync adjustments to apply consistent colour across the set. Use the Synchronise Settings dialog to specify which settings to sync (typically: White Balance, HSL, Colour Grading — but not Exposure, which varies per image)."}, {"title": "Final Review", "body": "Grid view review at thumbnail size. Images that visually stand out in tone or colour need individual attention. Aim for a gallery that looks cohesive — like it was shot under the same light throughout."}]}'),
  (v_l2, 'callout', 3, '{"variant": "tip", "title": "Adaptive Presets — The Future of AI Grading", "body": "Lightroom Adaptive Presets (2024+) apply adjustments that respond to the specific content of each image. An adaptive portrait preset, for example, automatically applies skin-warm adjustments to the faces it detects and different adjustments to the background — even though you applied one preset. This is the closest thing to per-image intelligent grading in a fully automated form."}'),
  (v_l2, 'expert_note', 4, '{"title": "Colour Grading with the Tone Curve and Colour Grading Wheels", "body": "Beyond the Basic panel, Lightroom''s Tone Curve and Colour Grading wheels give precise control that AI Auto cannot replicate.\n\nThe Tone Curve maps input brightness to output brightness. A classic portrait S-curve: lift the shadows slightly (adds lift and reduces contrast in dark areas), steepen the midtone section (increases contrast in the main subject range), gently rolloff the highlights (prevents blown whites).\n\nColour Grading wheels (Shadows, Midtones, Highlights) add colour tints to each tonal range independently. Classic film-inspired look: push the shadows slightly toward teal-blue, the highlights slightly toward warm yellow-orange. This creates depth and warmth simultaneously.\n\nThese controls are not AI, but they produce the distinctive colour signature that makes your work recognisable. The AI workflow handles the time-consuming per-image work; your manual curve and colour grading decisions create the signature look applied to everything."}');

  -- ── L6.3: Building your signature preset ─────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l3, 'text', 1, '{"html": "<h2>Building Your Signature Look</h2><p>A signature look is a consistent colour style that makes your portfolio immediately recognisable. It is not a filter — it is a deliberate set of creative decisions applied consistently across your work. Building a signature look takes experimentation, reference gathering, and iteration. Once built, it is one of your strongest business assets: clients hire you partly because they know what your work will look like.</p>"}'),
  (v_l3, 'steps', 2, '{"title": "Signature Preset Development Process", "steps": [{"title": "Gather Visual References", "body": "Find 20-30 images that represent the look you want — from photographers you admire, fashion editorials, film stills. Save to a dedicated folder. This is your mood board. Identify common characteristics: are they warm or cool? High or low contrast? Saturated or muted? Where is the colour in the shadows vs highlights?"}, {"title": "Deconstruct One Image", "body": "Choose one of your own photos with neutral, balanced light. Start from zero adjustments in Lightroom. Rebuild the look from your reference mood board, one adjustment at a time. Exposure curve first, then colour balance, then HSL adjustments. Take notes on what each change does."}, {"title": "Refine Across Different Images", "body": "Apply your draft preset to 20 images of different exposures and lighting conditions. Does it hold up in shade? In direct sun? On different skin tones? If the preset looks wrong on certain images, identify which adjustment is causing it and build in tolerance."}, {"title": "Test on a Real Client Gallery", "body": "Apply the preset to a full session (use a session from your archive — do not experiment on a live client delivery). Review the gallery as a whole. Does it look cohesive? Do all images feel like they belong together? Ask a colleague for feedback without telling them what you changed."}, {"title": "Save and Version", "body": "Save as a named Lightroom preset: Your Name Portrait v1. Over time, you will evolve the look — save as v2, v3. Keep old versions for clients who return expecting the same look as their previous session."}]}'),
  (v_l3, 'case_study', 3, '{"title": "Building a Signature Warm-Documentary Look", "context": "A Lusaka photographer wanted a warm, organic signature look — influenced by film photography and editorial documentary style. They had been grading inconsistently across sessions, making it hard to build a cohesive portfolio.", "action": "Spent one afternoon gathering references (30 images from documentary photographers they admired). Identified the look: warm shadows with slight teal, bright-but-not-blown highlights, muted but not desaturated colours, gentle film grain. Built from scratch on one of their own outdoor portraits. Iterated across 50 images. Finalised after 2 weeks of refinement.", "result": "Consistent gallery look across all portrait and event work. Portfolio immediately distinguishable from peers. First Instagram post after implementing the new look received the highest engagement of any post to date. Client response in booking inquiries: three clients specifically mentioned they loved the consistent style of the portfolio."}'),
  (v_l3, 'checklist', 4, '{"title": "Signature Preset Completion Checklist", "items": ["Gathered 20+ visual references that represent the target look", "Built the preset from scratch on a neutral test image (not applied to a photo that was already processed)", "Tested the preset on at least 20 different images across lighting conditions", "Tested on different skin tones — does it hold up across diverse subjects?", "Received feedback from at least one other photographer", "Saved with a clear version name", "Applied to a full real gallery and reviewed for cohesion"]}');

  -- ── L6.4: Mixed lighting ──────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l4, 'text', 1, '{"html": "<h2>Making Mixed Lighting Look Intentional</h2><p>Indoor events, wedding receptions, corporate dinners — these environments combine multiple light sources at different colour temperatures simultaneously: tungsten room lights (2800K), flash (5500K), window light (6000K+), and LED colour washes (variable). The result in RAW files is colour inconsistency that makes white balance correction alone insufficient.</p><p>AI-assisted mixed lighting correction works on two levels: <strong>global white balance</strong> (correcting the dominant overall colour cast) and <strong>selective local correction</strong> using AI masking to treat different areas of the image differently based on their dominant light source.</p>"}'),
  (v_l4, 'steps', 2, '{"title": "Mixed Lighting Correction Workflow", "steps": [{"title": "Set a Global Reference White Balance", "body": "In Lightroom, find an image where you have clear access to a neutral object (white tablecloth, white shirt, grey card). Use the Eyedropper tool to click the neutral area — this sets the white balance to neutralise that reference point. Note the Temperature and Tint values. Apply these values to all images from the same environment."}, {"title": "Address Remaining Colour Casts with AI Masking", "body": "For images where different light sources illuminate different areas: use Lightroom AI Masking. Add mask for the face/subject (which may be lit by flash — cooler). Add a separate mask for the background or ambient areas (lit by tungsten — warmer). Adjust white balance separately per mask to balance the two sources."}, {"title": "Use the HSL Panel for Persistent Casts", "body": "If tungsten light has rendered oranges/reds with an unrealistic cast, use the HSL panel: target the Orange and Red hues, reduce their saturation slightly, and nudge their hue toward a more neutral skin tone. This corrects the colour without changing white balance globally."}, {"title": "Accept Some Variation — Blend It Intentionally", "body": "Not all mixed lighting needs to be corrected to neutral. Sometimes the warm tungsten on the background and the cooler flash on the subject creates natural depth and separation. The rule: if the colour variation looks intentional and adds to the mood, keep it. If it looks like a mistake, correct it."}]}'),
  (v_l4, 'callout', 4, '{"variant": "tip", "title": "Shoot a Grey Card at Every Venue", "body": "A 5-second grey card shot at each new room or lighting environment gives you a reliable white balance reference. Photograph your Colour Checker Passport or a Lastolite grey card, set white balance from it in Lightroom, and sync to all images from that area. This alone eliminates 80% of mixed lighting correction work."}'),
  (v_l4, 'comparison_table', 3, '{"title": "Mixed Lighting Scenarios and Solutions", "headers": ["Scenario", "Problem", "AI Solution"], "rows": [["Indoor event: tungsten + flash", "Warm background, cool subjects", "Separate AI masks for subject and background — correct WB per mask"], ["Window + overhead office lighting", "Half the face warm, half cool", "AI face mask with WB adjustment; Lightroom AI Auto on tonal balance"], ["Wedding reception: LED colour wash", "Subject has coloured cast from venue lights", "HSL panel targeting the affected hue range; reduce saturation of cast colour"], ["Outdoor: shade + direct sun", "Subject in shade is blue, background in sun is warm", "Correct WB for subject; accept warm background or cool it with ambient mask"]]}');

  -- ── L6.5: Expert — colour science ────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l5, 'text', 1, '{"html": "<h2>How AI Colour Models Work</h2><p>This lesson is for photographers who want to understand the technical foundation of AI colour grading tools. It is not required knowledge — but it makes you a more precise operator who can push tools further and troubleshoot problems more accurately.</p>"}'),
  (v_l5, 'expert_note', 2, '{"title": "AI Colour Grading: How Models Are Trained and Applied", "body": "AI colour grading (as implemented in tools like Lightroom Auto, Luminar''s AI-driven adjustments, and dedicated tools like Perfectly Clear) uses one of two approaches:\n\n1. REGRESSION-BASED AUTO EXPOSURE: The model was trained on pairs of images (original camera output vs professional-edited version) and learned to predict the adjustments a professional would make. Lightroom Auto (and to some extent Camera Raw Auto) works this way — it predicts the tonal adjustments that would improve the image based on learned patterns from thousands of professional edits.\n\n2. STYLE TRANSFER: More advanced tools use neural style transfer, which applies the visual characteristics of a reference style to a target image at a deeper level than curve adjustments. The network learns colour relationships, contrast patterns, and textural qualities from a reference set and applies them to new images. This is closer to how AI presets work in tools like Luminar.\n\n3. COLOUR CORRECTION WITH SEMANTIC UNDERSTANDING: The most advanced implementations (Lightroom Adaptive Presets, some Adobe Sensei features) apply different adjustments to different semantic regions of the image — the subject gets different treatment than the background, based on AI subject recognition. This is effectively AI-powered dodging and burning.\n\nThe practical implication: these tools work best on images that resemble their training data. A Lightroom Auto model trained primarily on Western editorial photography may apply adjustments that are subtly miscalibrated for African skin tones or equatorial lighting conditions. Always check results against your actual subject — do not trust AI auto-grade blindly, especially on skin tone accuracy."}'),
  (v_l5, 'key_takeaway', 4, '{"title": "Colour Science for Practitioners", "points": ["AI colour grading predicts adjustments from training data — it is not neutral or objective. Check skin tone accuracy on your specific client base.", "Lightroom Auto and Adaptive Presets use regression models trained on professional edit pairs.", "Style transfer AI applies visual characteristics from a reference style — this is how AI presets achieve distinctive looks.", "Models trained on predominantly Western subjects may produce subtly incorrect skin tone adjustments for African subjects. Calibrate your presets on your actual clients.", "Understanding the model type helps you know when to trust AI output and when to override it."]}');

  -- ── L6.6: Colour accuracy screen vs print ────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l6, 'text', 1, '{"html": "<h2>Colour Accuracy: Screen vs Print Delivery</h2><p>A perfectly graded image on your editing monitor can look significantly different when printed or viewed on another screen. This is a colour management problem — the colours you see are relative to the display device, not absolute. Without colour management, what looks right to you may look wrong to your client.</p>"}'),
  (v_l6, 'steps', 2, '{"title": "Setting Up Colour-Accurate Delivery", "steps": [{"title": "Calibrate Your Monitor", "body": "Use a hardware colorimeter (X-Rite i1Display, Datacolor Spyder) to create a display profile. Monthly calibration is the professional standard — displays drift over time. Without calibration, your grading decisions are made relative to an unknown standard."}, {"title": "Export in sRGB for All Web and Social Delivery", "body": "sRGB is the safe, universal standard. Every browser, every social platform, every phone converts images to sRGB for display. Export all web/social images as sRGB. If you export Adobe RGB for web delivery, images appear desaturated on uncalibrated screens (which is most screens)."}, {"title": "Check with Your Print Lab for Print Delivery", "body": "Ask your lab: which colour space do you accept? Most accept sRGB and handle their own conversion. Some professional labs accept Adobe RGB (1998) for wide-gamut work. Follow their specifications precisely."}, {"title": "Soft Proof Before Large Prints", "body": "In Lightroom or Photoshop, use Soft Proofing (View > Soft Proofing in Lightroom) to simulate how your image will look when printed on a specific paper with a specific ink profile. Your lab should provide ICC profiles for their paper/printer combinations. This preview helps you catch problems before expensive large-format prints are produced."}]}'),
  (v_l6, 'checklist', 3, '{"title": "Colour Management Checklist", "items": ["Monitor calibrated within the last 30 days", "Lightroom colour space set to sRGB for standard exports", "Confirmed with print lab which colour space and file format they require", "Soft proofing profile downloaded from print lab for large format orders", "All client galleries exported and reviewed on a second screen (phone or tablet) before delivery", "Gallery delivery platform colour management settings confirmed (most platforms transcode to sRGB)"]}'),
  (v_l6, 'callout', 4, '{"variant": "important", "title": "The Most Common Client Colour Complaint", "body": "The most frequent colour complaint from clients is that images look different on their phone than in the gallery. This is usually a colour space mismatch. Ensuring your gallery delivery platform processes images as sRGB resolves the vast majority of these complaints before they happen."}');

  -- ── L6.7: Live Session 2 (Meeting) ────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_lm, 'text', 1, '{"html": "<h2>Live Session 2: Colour Grading Workshop</h2><p>In this session your instructor will live-grade a full portrait session from scratch, showing the complete AI-assisted colour grading workflow in real time. You will see how to build a signature preset, handle mixed lighting, and achieve gallery consistency in under 30 minutes.</p><ul><li>Live demonstration: building a grading preset from scratch</li><li>Mixed lighting correction — live problem-solving</li><li>Sync workflow across a gallery</li><li>Q&A: your specific colour grading challenges</li><li>Review of student work — bring a gallery you are struggling with</li></ul>"}'),
  (v_lm, 'meeting', 2, '{"meeting_id": "", "title": "Live Session 2: Colour Grading Workshop", "start_time": "TBD — check course announcements for scheduled date", "description": "30-minute live colour grading demonstration and Q&A. Bring a gallery you want to work on."}'),
  (v_lm, 'checklist', 3, '{"title": "Prepare for the Colour Grading Session", "items": ["Completed all Module 6 lessons before attending", "Have at least one gallery or session ready to discuss — a problem you are currently facing", "Monitor calibrated (or note that it is not — we can discuss this)", "Written down 2 colour grading questions you want answered in the session", "Your current signature preset ready to share (screenshot or export) for feedback"]}');

  -- ── Module 6 Checkpoint Quiz ──────────────────────────────────────────
  DELETE FROM quizzes WHERE lesson_id = v_lq;
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES (v_lq, 'quiz', 1, '{"quiz_id": ""}');
  INSERT INTO quizzes (lesson_id, title, pass_threshold, max_attempts)
    VALUES (v_lq, 'Module 6: AI Colour Grading', 70, 3) RETURNING id INTO v_quiz_id;
  UPDATE content_blocks SET content = jsonb_build_object('quiz_id', v_quiz_id::text)
    WHERE lesson_id = v_lq AND type = 'quiz';

  INSERT INTO quiz_questions (quiz_id, question, options, correct_indices, explanation, position) VALUES
    (v_quiz_id, 'A photographer exports a portrait gallery in Adobe RGB colour space for delivery via a client gallery website. The client reports the images look flat and desaturated. What is the most likely cause?',
     '["The images were graded incorrectly", "Adobe RGB images look desaturated on uncalibrated or sRGB-only displays, which includes most consumer screens and browsers", "The gallery platform compressed the images too heavily", "The client is viewing on a mobile device, which cannot display colour photography"]',
     '{1}', 'Adobe RGB contains colours outside the sRGB gamut. On screens that do not handle colour space conversion, these additional colours appear desaturated. Deliver in sRGB for all web and gallery use.', 1),
    (v_quiz_id, 'What does a Lightroom Adaptive Preset do differently from a standard Lightroom preset?',
     '["It saves the preset to the cloud for access on all devices", "It applies different adjustments to different semantic areas of each image (subject, background, sky) based on AI content recognition", "It adapts to your editing style over time by learning from your previous adjustments", "It automatically applies different strengths based on the image''s ISO level"]',
     '{1}', 'Adaptive Presets use AI to recognise image content and apply contextually appropriate adjustments per region — e.g., portrait-specific adjustments on faces while applying different settings to backgrounds.', 2),
    (v_quiz_id, 'A wedding photographer has 400 images from a reception with heavy orange tungsten light and flash-lit subjects. Which workflow step most efficiently corrects the colour cast?',
     '["Manually adjust white balance on each of the 400 images", "Set white balance from a grey reference shot taken in the venue, sync to all images, then use AI face masking for residual per-image corrections", "Convert all images to black and white to avoid the colour problem", "Apply maximum Clarity and Texture to override the colour issue"]',
     '{1}', 'A venue reference shot provides a reliable starting white balance. Syncing it to all images handles the global correction. AI masking then handles per-image residual differences efficiently.', 3),
    (v_quiz_id, 'What is the purpose of monitor calibration for photographers?',
     '["To make the screen brighter for editing in bright rooms", "To create a display profile that corrects for the monitor''s colour deviation, ensuring that colours on screen accurately represent the data in the file", "To synchronise the monitor''s colour settings with Lightroom automatically", "To reduce eye strain during long editing sessions"]',
     '{1}', 'Monitors drift from factory calibration over time and vary between models. Calibration creates a profile that corrects these deviations, ensuring you are editing relative to a known colour standard.', 4),
    (v_quiz_id, 'When should you use Lightroom Soft Proofing?',
     '["For every image before posting to social media", "Before ordering large-format prints — to preview how the image will look rendered on a specific paper/printer combination", "To check how images will look on mobile devices", "To apply a film grain effect that simulates printed photos"]',
     '{1}', 'Soft Proofing simulates the colour rendering of a specific print output profile. It helps identify colour shifts before committing to expensive large-format prints.', 5);

  RAISE NOTICE '✓ Module 6 content loaded (6 lessons + meeting + quiz).';
END $$;
