DO $$
DECLARE
  v_course_id uuid;
  v_mod_id    uuid;
  v_l1 uuid; v_l2 uuid; v_l3 uuid; v_l4 uuid; v_l5 uuid; v_l6 uuid; v_lq uuid;
  v_quiz_id   uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ai-photography-practical-course';
  SELECT id INTO v_mod_id FROM modules WHERE course_id = v_course_id AND position = 7;
  SELECT id INTO v_l1 FROM lessons WHERE module_id = v_mod_id AND position = 1;
  SELECT id INTO v_l2 FROM lessons WHERE module_id = v_mod_id AND position = 2;
  SELECT id INTO v_l3 FROM lessons WHERE module_id = v_mod_id AND position = 3;
  SELECT id INTO v_l4 FROM lessons WHERE module_id = v_mod_id AND position = 4;
  SELECT id INTO v_l5 FROM lessons WHERE module_id = v_mod_id AND position = 5;
  SELECT id INTO v_l6 FROM lessons WHERE module_id = v_mod_id AND position = 6;
  SELECT id INTO v_lq FROM lessons WHERE module_id = v_mod_id AND position = 7;

  DELETE FROM content_blocks WHERE lesson_id IN (v_l1,v_l2,v_l3,v_l4,v_l5,v_l6,v_lq);

  -- ─── L7.1: What generative AI can and cannot do in 2025 ──────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l1,'text',1,'{"html":"<h2>The Reality of Generative AI in Photography (2025)</h2><p>Generative AI has transformed from a novelty into a professional tool — but photographers who use it blindly get burned, and those who refuse it get left behind. The truth is somewhere more interesting: <strong>generative AI is a powerful creative partner with specific strengths and hard limitations</strong>.</p><p>This lesson gives you an honest, technical picture so you can deploy these tools at the right moment and avoid the mistakes that damage client trust.</p>"}'),
  (v_l1,'comparison_table',2,'{"headers":["Capability","What AI Does Well","Where It Struggles"],"rows":[["Sky replacement","Seamless, photorealistic on open skies","Poles, branches, complex silhouettes"],["Object removal","Clean fills on textured backgrounds","Glass reflections, shadows cast by subject"],["Portrait skin","Smoothing, pore reduction at speed","Preserving authentic texture for print"],["Generative fill","Extending canvas, adding plausible elements","Hands, text, repeated patterns with logic"],["Upscaling","4×–8× with detail hallucination","Fine hair, dense foliage at extreme zoom"],["Style transfer","Mood, colour tone, artistic look","Client likeness, brand colour accuracy"],["Noise reduction","Preserving edge detail in low light","Very high ISO above ISO 51200"]]}'),
  (v_l1,'expert_note',3,'{"title":"Why \"AI-Generated\" vs \"AI-Assisted\" Matters Professionally","body":"The industry is converging on a critical distinction. AI-assisted means the photographer captured the original image, made creative decisions, and used AI as a technical tool (noise reduction, object removal). AI-generated means the AI created the image from a prompt. Most commercial clients and stock agencies treat these differently — many stock platforms (Getty, Shutterstock) ban AI-generated images but permit AI-assisted processing. Know which category your work falls into before licensing or selling."}'),
  (v_l1,'callout',4,'{"type":"warning","title":"The Hallucination Problem","body":"Generative AI invents content it cannot see. Ask it to extend a photo beyond its border and it will generate plausible-looking — but fabricated — pixels. For documentary, journalism, or forensic photography this is unacceptable. For commercial lifestyle work it may be fine with disclosure. Understand your genre''s ethics before generating."}'),
  (v_l1,'key_takeaway',5,'{"points":["Generative AI excels at repetitive technical tasks (sky swap, background fill, upscaling) but struggles with logic-dependent content (hands, text, reflections).","AI-assisted and AI-generated are legally and ethically different categories — know which you are producing.","The best professional workflow combines AI speed with human judgment, not AI instead of human judgment.","Every generated pixel is a liability if not disclosed to clients who require authenticity."]}');

  -- ─── L7.2: Adobe Firefly — generative fill, object removal, canvas extension ─
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l2,'text',1,'{"html":"<h2>Adobe Firefly Inside Photoshop</h2><p>Adobe Firefly is trained exclusively on licensed Adobe Stock imagery, meaning its outputs are commercially safer than models trained on scraped web data. Integrated directly into Photoshop''s contextual taskbar since version 25.0, it makes generative editing available without leaving your existing workflow.</p><p>This lesson walks through the three Firefly tools you''ll use every week in client work.</p>"}'),
  (v_l2,'tool_spotlight',2,'{"name":"Adobe Firefly (Photoshop)","purpose":"Contextual generative AI trained on licensed imagery — safe for commercial use","url":"https://firefly.adobe.com","pros":["Commercially licensed training data","Integrated into Photoshop — no separate app","Content credentials embedded automatically","Generative Fill + Generative Expand + Object Removal"],"cons":["Requires paid Creative Cloud subscription","Slower than local models","Struggles with complex foreground–background relationships"]}'),
  (v_l2,'steps',3,'{"steps":[{"title":"Generative Fill — Remove an Unwanted Object","body":"Select the object with the Object Selection tool (W). Expand the selection by 10–20 px (Select > Modify > Expand). Open the Contextual Taskbar and click Generative Fill. Leave the prompt blank — blank = contextual fill based on surroundings. Click Generate. Photoshop creates 3 variations on a new Generative Layer; choose the best one."},{"title":"Generative Fill — Add a New Element","body":"Make a selection in an empty area of the frame. In the Contextual Taskbar, type a descriptive prompt: \"wooden cafe table, warm morning light\". Click Generate. Firefly places a photorealistic element into your selection. Use Warp or Transform to fine-tune perspective."},{"title":"Generative Expand — Canvas Extension","body":"Use the Crop tool, pull a handle beyond the photo edge. A marquee appears on the new empty area. Click Generative Expand in the taskbar. Add an optional prompt if you want to direct the content (e.g. \"forest path continuing\"). Generate 3 options and pick the best. Mask and blend if edges are imperfect."},{"title":"Object Removal Tool","body":"In Photoshop 2024+, find Remove Tool in the Healing group (J). Paint over the object. Photoshop automatically samples surroundings and fills. For complex objects, try the Generative Fill approach instead — the Remove Tool works best on simple backgrounds."}]}'),
  (v_l2,'ai_prompt',4,'{"prompt":"I have a portrait shot outdoors where a telephone pole is bisecting my subject''s head. The background is a blurred green park. Walk me through the exact Photoshop Generative Fill steps to remove the pole and what settings give the cleanest result.","tool":"Claude AI","label":"Practice — Get step-by-step guidance for your own problem"}'),
  (v_l2,'callout',5,'{"type":"info","title":"Content Credentials","body":"Firefly automatically embeds Adobe Content Credentials into generated images — a cryptographic record that the image contains AI-generated content. This is increasingly required by clients, publications, and platforms. You can verify credentials at contentcredentials.org."}');

  -- ─── L7.3: Luminar Neo Sky AI ────────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l3,'text',1,'{"html":"<h2>Luminar Neo Sky AI: Realistic Replacements and Honest Limitations</h2><p>Luminar Neo''s sky replacement feature is the benchmark for one-click sky swaps. Unlike Photoshop''s manual sky replacement (which requires hand-masking), Neo builds a sky mask automatically and re-lights the foreground to match the new sky''s colour temperature and direction.</p><p>For wedding and landscape photographers in particular, this tool can rescue a technically perfect shot with a dull white sky — a common problem in Zambia''s rainy season.</p>"}'),
  (v_l3,'steps',2,'{"steps":[{"title":"Basic Sky Replacement","body":"Open your image in Luminar Neo. Go to Edit > Sky AI. Select a sky from the built-in library or click the + icon to import your own sky photo. Luminar automatically masks the sky and adjusts foreground lighting. Use the Relight Scene slider to blend ambient light from the new sky into the foreground."},{"title":"Horizon Blending","body":"If the horizon line looks artificial, increase the Horizon Blending slider (0–100). For scenes with trees or complex silhouettes, also increase Horizon Position slightly to push the sky–land boundary up behind foliage gaps."},{"title":"Atmospheric Haze","body":"Real skies create haze on distant objects. Enable Atmospheric Haze in Sky AI and set it to 10–30% — this adds a light fog effect to distant elements, which makes the composite feel physically plausible."},{"title":"Sky Matching Colour","body":"Use the Sky Global Colour slider to shift the hue of the replaced sky slightly warmer or cooler to match the original light on your subject. Then use Relight Scene to propagate that colour into shadows and midtones of the foreground."},{"title":"Exporting Without Artefacts","body":"Export at maximum quality (TIFF or full-quality JPEG). Sky AI masking degrades at JPEG quality below 85. If you need to continue editing in Photoshop, export as TIFF with layers if Luminar supports your subscription level."}]}'),
  (v_l3,'case_study',3,'{"title":"Wedding Sky Rescue — Lusaka, Rainy Season","context":"A wedding photographer shot an outdoor ceremony at 14:00 in November. The sky was a flat, featureless white — completely overblown — but the light on the couple was perfect. The client expected dramatic golden-hour images from the preview gallery.","action":"The photographer used Luminar Neo Sky AI to replace the white sky with a dramatic pre-sunset sky shot in the Copperbelt the previous month. Relight Scene at 40% pushed warm amber tones into the couple''s skin and clothing shadows. Atmospheric Haze at 15% added depth to the distant trees.","result":"The final images were indistinguishable from genuine golden-hour shots. The photographer disclosed \"sky enhancement\" in their standard editing terms sent to the client on booking — the client was delighted, not deceived. The images were delivered on time without scheduling a reshoot."}'),
  (v_l3,'callout',4,'{"type":"warning","title":"Where Sky AI Fails","body":"Sky AI struggles with: (1) Complex silhouettes — dense trees, chain-link fences, mesh fabric all create masking errors. (2) Puddles and wet surfaces that reflect the original sky — these remain the old colour and betray the composite. (3) Glassware or windows showing sky. Always zoom to 100% and check these areas before delivering."}');

  -- ─── L7.4: Midjourney for photographers ──────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l4,'text',1,'{"html":"<h2>Midjourney for Photographers: Concept Boards and Client Briefs</h2><p>Most photographers first encounter Midjourney as a novelty — they type a prompt and are amazed by the result. Professionals use it differently: <strong>as a client communication tool</strong>. Instead of spending time on a mood board built from other photographers'' work (which carries copyright risk), you generate a bespoke concept board in minutes using Midjourney''s style parameters.</p><p>This is not about replacing photography. It''s about helping clients visualise what you''re proposing before a single frame is shot.</p>"}'),
  (v_l4,'tool_spotlight',2,'{"name":"Midjourney v6","purpose":"Text-to-image model for mood boards, concept visualisation, and client pre-visualisation","url":"https://midjourney.com","pros":["Photorealistic results with correct lighting","--style raw for less stylised output","Image prompting with --iw for style blending","Fast iteration for client feedback"],"cons":["No commercial licence for AI-generated photography presented as real photographs","Requires Discord or web interface","Hands and text still inconsistent","Cannot replicate specific real-world locations accurately"]}'),
  (v_l4,'steps',3,'{"steps":[{"title":"Build a Style Reference Board","body":"In Midjourney, start with a lighting and mood reference: /imagine prompt: outdoor portrait, golden hour backlight, Zambian savanna, shallow depth of field, 85mm lens --style raw --ar 3:2. Generate 4 variations. Upscale your favourite. This becomes a lighting reference image for your shoot brief."},{"title":"Client Colour Direction","body":"Show the client two or three Midjourney variations with different colour palettes. Prompt for warm golden vs cool blue hour vs overcast soft light. Ask: \"Which of these three feels closest to what you''re imagining?\" This replaces a 20-minute verbal description with a 2-second visual decision."},{"title":"Prop and Set Direction","body":"Use Midjourney to visualise proposed sets before renting or building them. /imagine prompt: minimalist product photography set, white seamless, ring light, wooden props, luxury skincare --ar 1:1 --style raw. Share with client to confirm before shoot day."},{"title":"Image Prompting for Style Matching","body":"If a client sends you a reference image, upload it to Midjourney with /imagine [image URL] their style description --iw 0.75. The --iw flag sets image weight — how strongly Midjourney follows the reference image. This helps translate a client''s Pinterest board into a Zambian context."}]}'),
  (v_l4,'ai_prompt',4,'{"prompt":"I have a client who wants corporate headshots with a modern, approachable feel — not stiff or formal. They can''t visualise what I''m describing. Write me 3 Midjourney prompts that would generate concept board images showing three different interpretations of ''modern approachable corporate portrait'' that I can show them to get alignment before the shoot.","tool":"Claude AI","label":"Generate client concept board prompts"}'),
  (v_l4,'ai_prompt',5,'{"prompt":"My client loved concept option 2 from the board — it had an outdoor rooftop setting with warm late-afternoon light and a relaxed pose. Now help me translate this into a detailed shoot brief: location requirements, time of day, lighting equipment, wardrobe direction, and posing notes. Format it as a professional PDF-ready brief.","tool":"Claude AI","label":"Convert approved concept into a shoot brief"}');

  -- ─── L7.5: Text-to-image prompting masterclass ───────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l5,'text',1,'{"html":"<h2>Text-to-Image Prompting Masterclass</h2><p>The difference between a mediocre AI image and a stunning one is almost never the model — it''s the prompt. Prompting is a skill, and like composition or exposure, it follows learnable rules. Once you understand the structure, you can get consistent, professional results across any text-to-image model (Midjourney, Firefly, Stable Diffusion, DALL·E).</p><p>This lesson teaches the <strong>anatomy of a professional prompt</strong> and gives you a repeatable framework.</p>"}'),
  (v_l5,'steps',2,'{"steps":[{"title":"The Six-Part Prompt Structure","body":"Every strong prompt has: (1) Subject — who/what is the focus. (2) Action/Pose — what they are doing. (3) Setting — where, with what background. (4) Lighting — the quality and direction of light. (5) Camera/Lens — focal length, depth of field, format. (6) Style/Mood — cinematic, editorial, documentary, fine art."},{"title":"Subject Specificity","body":"Weak: ''a woman''. Strong: ''a Zambian woman in her 30s, natural hair, confident posture, wearing indigo wax print fabric''. AI models respond to specificity. The more precise your subject description, the less the model guesses — and guesses wrong."},{"title":"Lighting Language","body":"Use photography lighting terms the model understands: ''Rembrandt lighting'', ''butterfly lighting'', ''golden hour backlight'', ''overcast diffused light'', ''practical tungsten fill'', ''beauty dish at 45 degrees''. These terms appear in the model''s training data as technical photography concepts."},{"title":"Negative Prompting","body":"In Stable Diffusion and some other models, you can specify what NOT to generate. --no blur, low quality, watermark, extra fingers, text. In Midjourney, append --no [unwanted elements]. Negative prompts dramatically reduce common artefacts."},{"title":"Iteration and Variation","body":"Generate 4 variations. Pick the best. Use that as an image prompt (--iw in Midjourney) for the next round. Iterate 2–3 times. Professional concept images often take 3–5 rounds to reach the quality level a client brief requires."}]}'),
  (v_l5,'ai_prompt',3,'{"prompt":"I want to photograph a luxury skincare brand targeting Zambian women aged 25–40. Write 5 Midjourney prompts that would generate reference images for: (1) hero product shot, (2) lifestyle in-home scene, (3) outdoor portrait with product, (4) flat lay composition, (5) editorial campaign image. Each prompt should follow the six-part structure: subject, action, setting, lighting, camera/lens, style.","tool":"Claude AI","label":"Generate brand shoot reference prompts"}'),
  (v_l5,'ai_prompt',4,'{"prompt":"I generated this Midjourney image [describe an image you''ve made] but it has a problem: [describe the issue — e.g. the hands look wrong, the lighting is too harsh, the background is distracting]. How do I fix this with a prompt revision? What specific language should I add, change, or use as a negative prompt?","tool":"Claude AI","label":"Troubleshoot a bad AI image output"}'),
  (v_l5,'ai_prompt',5,'{"prompt":"I''m shooting a wedding next month in Livingstone near Victoria Falls. Generate 3 Midjourney prompts I could use to show the couple concept images for: their getting-ready portraits (morning light, candid), their outdoor ceremony (Victoria Falls mist in background), and their reception details (candles, flowers, African decor). Make each prompt specific enough to get a usable concept board image.","tool":"Claude AI","label":"Wedding pre-visualisation prompts"}'),
  (v_l5,'expert_note',6,'{"title":"Prompt Injection and Model Bias","body":"Every text-to-image model carries biases from its training data — predominantly Western, often defaulting to light skin tones and European settings unless instructed otherwise. When working for African clients and contexts, you must explicitly specify: nationality or ethnicity, local environment or architecture, culturally appropriate clothing and props, and local names or concepts where relevant. This is not just cultural sensitivity — it produces more accurate concept boards for your actual market. Models like Midjourney v6 respond well to specific cultural direction when prompted correctly."}');

  -- ─── L7.6: Disclosure and ethics ─────────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l6,'text',1,'{"html":"<h2>Disclosure and Ethics: When and How to Tell Clients You Used AI</h2><p>This is the lesson most AI photography courses skip. They show you the tools and leave the ethics as an afterthought. We''re doing it the opposite way — because your reputation is built on trust, and trust requires honesty about your process.</p><p>This doesn''t mean confessing every Lightroom adjustment. It means having a clear, professional policy about what constitutes disclosure-worthy AI use, communicating it proactively, and building it into your contracts before you''re asked.</p>"}'),
  (v_l6,'callout',2,'{"type":"info","title":"The Disclosure Spectrum","body":"Not all AI use requires the same level of disclosure. Think in tiers: Tier 1 (always disclose) — AI-generated images presented as photographs, replacing real elements with AI-generated ones (sky with people, fake locations). Tier 2 (recommend disclosing) — Generative fill of objects not present at the shoot, AI people/faces added to crowd scenes. Tier 3 (standard editing, no special disclosure) — AI noise reduction, AI sharpening, AI-assisted skin smoothing, AI sky replacement of a genuine sky with another genuine sky."}'),
  (v_l6,'checklist',3,'{"items":["Add an AI Usage clause to your standard client contract before shooting","Define clearly what types of AI editing your workflow includes","State whether AI-generated content (Firefly, Midjourney) will appear in final deliverables","Specify your metadata and Content Credentials policy","Clarify licensing: can the client use AI-assisted images for commercial advertising?","Include a re-edit right if the client later objects to AI processing","For editorial clients, check their specific AI policy before accepting the commission"]}'),
  (v_l6,'ai_prompt',4,'{"prompt":"Draft a professional AI Usage Policy section for a photography service contract. I''m a commercial photographer based in Zambia. My standard workflow includes: AI noise reduction (Lightroom Denoise), AI-assisted culling (Imagen AI), sky replacement in Luminar Neo (replacing real skies with real skies), and occasional Photoshop Generative Fill to remove distracting objects. I sometimes use Midjourney for client concept boards before shooting (always clearly labelled as AI concept images, never delivered as photographs). Write a clear, plain-English policy section that I can add to my booking contract.","tool":"Claude AI","label":"Draft your personal AI disclosure contract clause"}'),
  (v_l6,'callout',5,'{"type":"warning","title":"Stock Photography and AI","body":"If you license images through Getty Images, Shutterstock, or Adobe Stock, check each platform''s current AI policy before submitting. As of 2025: Getty bans AI-generated images. Adobe Stock accepts AI-generated images on a separate track with mandatory disclosure. Shutterstock has its own Shutterstock.AI platform. Policies are evolving fast — check before submitting any image with AI-generated content."}'),
  (v_l6,'key_takeaway',6,'{"points":["Disclosure is a professional standard, not an admission of weakness — clients respect photographers who are transparent about their process.","Build your AI policy into your contract before a client asks, not after a dispute arises.","Generative AI that creates content not present at the shoot requires disclosure; AI that processes content that was there (noise, sharpening, sky) is standard editing.","Stock agency policies vary significantly — always check the current policy per platform before submitting AI-assisted or AI-generated work."]}');

  -- ─── L7.Q: Quiz ──────────────────────────────────────────────────────────
  DELETE FROM quizzes WHERE lesson_id = v_lq;
  INSERT INTO content_blocks (lesson_id, type, position, content)
  VALUES (v_lq, 'quiz', 1, '{"quiz_id": ""}');

  INSERT INTO quizzes (lesson_id, title, description, passing_score, max_attempts)
  VALUES (v_lq, 'Module 7 Checkpoint — Generative AI', 'Test your understanding of generative AI tools, prompting, and professional ethics.', 80, 3)
  RETURNING id INTO v_quiz_id;

  UPDATE content_blocks
  SET content = jsonb_build_object('quiz_id', v_quiz_id::text)
  WHERE lesson_id = v_lq AND type = 'quiz';

  INSERT INTO quiz_questions (quiz_id, question, type, options, correct_answer, explanation, position) VALUES
  (v_quiz_id,
   'A client asks you to deliver a portrait where you used Midjourney to replace their face with a more "photogenic" AI-generated version. What should you do?',
   'multiple_choice',
   '["Deliver it — the client won''t know","Refuse or clearly disclose that the face is AI-generated, not the person","Only disclose if the client specifically asks","Deliver it but add a watermark saying AI-enhanced"]',
   'Refuse or clearly disclose that the face is AI-generated, not the person',
   'Replacing a real person''s face with an AI-generated face without disclosure is deceptive and potentially defamatory. This falls firmly in the Tier 1 always-disclose category — or may require refusing the job entirely.',
   1),
  (v_quiz_id,
   'Which of the following is the most significant advantage of Adobe Firefly over other generative AI tools for commercial photographers?',
   'multiple_choice',
   '["It produces more realistic images than other models","Its training data consists of licensed imagery, reducing commercial risk","It is free to use","It works offline without internet"]',
   'Its training data consists of licensed imagery, reducing commercial risk',
   'Firefly''s commercially licensed training data is its primary professional advantage. The resulting images carry lower IP risk for commercial use than models trained on scraped web data.',
   2),
  (v_quiz_id,
   'When using Luminar Neo Sky AI, what causes a "puddle problem" in outdoor shots?',
   'multiple_choice',
   '["The AI cannot process RAW files with water","Puddles reflect the original sky colour and are not replaced by Sky AI, revealing the composite","The software crashes when water is detected in the image","Puddles create noise patterns the AI amplifies"]',
   'Puddles reflect the original sky colour and are not replaced by Sky AI, revealing the composite',
   'This is one of Sky AI''s most common failure modes. The replaced sky changes the sky area, but reflections in water, glass, or wet surfaces retain the original sky colour — a clear tell that the sky was swapped.',
   3),
  (v_quiz_id,
   'Which of the following best describes how professional photographers should use Midjourney?',
   'multiple_choice',
   '["As a replacement for shooting — deliver Midjourney images as photographs","As a client communication tool to pre-visualise concepts before the shoot","For social media posts presented as their own photography","As a way to fill gaps in a portfolio without shooting"]',
   'As a client communication tool to pre-visualise concepts before the shoot',
   'Midjourney''s professional photography use case is concept boards and client pre-visualisation. Using AI-generated images as photographs or misrepresenting AI images as your own photography is unethical.',
   4),
  (v_quiz_id,
   'In the six-part prompt structure for text-to-image AI, which element most directly controls the quality of light in the generated image?',
   'multiple_choice',
   '["Subject","Setting","Lighting","Style/Mood"]',
   'Lighting',
   'The Lighting element (e.g. "Rembrandt lighting", "golden hour backlight", "overcast diffused") directly describes the quality, direction, and character of light. Models trained on photography respond well to these technical lighting terms.',
   5);

  RAISE NOTICE '✓ Module 7 (Generative AI) content loaded.';
END $$;
