DO $$
DECLARE
  v_course_id uuid;
  v_mod_id    uuid;
  v_l1 uuid; v_l2 uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'ai-photography-practical-course';
  SELECT id INTO v_mod_id FROM modules WHERE course_id = v_course_id AND position = 8;
  SELECT id INTO v_l1 FROM lessons WHERE module_id = v_mod_id AND position = 1;
  SELECT id INTO v_l2 FROM lessons WHERE module_id = v_mod_id AND position = 2;

  DELETE FROM content_blocks WHERE lesson_id IN (v_l1, v_l2);

  -- ─── L8.1: Mid-Course Project Brief ──────────────────────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l1,'text',1,'{"html":"<h2>Mid-Course Project: AI-Powered Photo Edit Portfolio</h2><p>You have completed seven modules covering the full AI photography workflow — from intelligent culling and background removal through colour grading and generative AI. Now it''s time to put it all together in one cohesive submission that demonstrates your mastery of these tools on your own images.</p><p>This project is your proof of competence. It is also the portfolio piece you will show to clients to demonstrate what AI-assisted photography editing can do for their business.</p><h3>Project Overview</h3><p>You will select a set of your own photographs, apply the techniques from Modules 1–7, and submit a before/after portfolio with a written process note explaining your tool choices.</p>"}'),
  (v_l1,'steps',2,'{"steps":[{"title":"Task 1 — Intelligent Cull and Select (Module 3)","body":"Start with a set of at least 40 raw images from a single shoot (any subject: portrait, product, landscape, event). Use Imagen AI, Lightroom AI Picker, or your preferred AI culling tool to cull down to your top 10 selects. Export a contact sheet PDF of your rejects and selects — the AI scores should be visible. Write 2–3 sentences explaining any images where you overrode the AI''s recommendation and why."},{"title":"Task 2 — Background Removal (Module 2)","body":"Choose 2 of your selected images and perform a professional background removal using the tool of your choice (Photoshop AI Remove Background, remove.bg, Luminar Neo). One image should have a complex edge (hair, fur, or fine detail). Replace the background with: (a) a simple studio-white background, and (b) a contextual background appropriate for the subject. Deliver both versions."},{"title":"Task 3 — AI Enhancement and Colour Grading (Modules 4–6)","body":"Take 3 of your selects through a full AI-assisted enhancement workflow: denoise with Lightroom Denoise or Topaz DeNoise AI, apply AI subject masking and targeted adjustments, and apply a colour grade appropriate for the subject/genre. Create a custom preset in Lightroom based on your grade and name it [YourName]_[Genre]_v1."},{"title":"Task 4 — Portrait Retouching (Module 5)","body":"If your images include a portrait, apply a complete AI-assisted retouch: frequency separation (or Photoshop Neural Filters for skin), teeth whitening (Luminar Neo or Photoshop), and eye enhancement. Deliver a before/after comparison at 100% crop showing the skin texture. If your images do not include portraits, substitute with a product shot requiring clean surface retouching."},{"title":"Task 5 — Generative AI Element (Module 7)","body":"Apply one generative AI technique to one of your images. Options: (a) Sky replacement with Luminar Neo Sky AI, (b) Object removal using Photoshop Generative Fill, (c) Canvas extension using Photoshop Generative Expand. Write a 3–5 sentence process note explaining: what you did, why you chose this tool, and whether you would disclose this technique to a client for this type of image."}]}'),
  (v_l1,'callout',3,'{"type":"info","title":"Submission Format","body":"Submit a single ZIP file containing: (1) Before/after JPEG pairs for each task, labelled T1_before.jpg / T1_after.jpg etc. (2) Your process notes as a single PDF or Word document. (3) Your Lightroom preset file (.lrtemplate or .xmp) from Task 3. Maximum file size: 50MB. Accepted formats: JPEG, PDF, DOCX, XMP, LRTEMPLATE."}'),
  (v_l1,'checklist',4,'{"items":["40+ raw images culled to 10 selects with contact sheet PDF","2 background removal images (each with white and contextual background versions)","3 images with full AI enhancement + colour grade pipeline","Custom Lightroom preset exported","1 portrait or product retouch with 100% crop before/after","1 generative AI edit with written process note and disclosure decision","All files labelled correctly in a single ZIP","Process notes PDF completed and included"]}'),
  (v_l1,'key_takeaway',5,'{"points":["This project is a portfolio piece — treat it as work you would show a real client.","Your process notes matter as much as the final images: they show you understand why, not just how.","You have 2 weeks to complete and upload your submission before the Live Review Session.","The Live Review Session (Module 8, Lesson 2) is where your instructor will give personalised feedback on your submission."]}');

  -- ─── L8.2: Live Session 3 — Project Review and Q&A ───────────────────────
  INSERT INTO content_blocks (lesson_id, type, position, content) VALUES
  (v_l2,'text',1,'{"html":"<h2>Live Session 3: Project Review and Q&A</h2><p>This is your third live session with your instructor. In this session, we will review submitted mid-course projects together, discuss common challenges and breakthroughs from the cohort, and answer questions that have accumulated over Modules 4–7.</p><p><strong>Make sure your project is submitted at least 24 hours before this session</strong> so your instructor has time to review it.</p><h3>What to Prepare</h3><ul><li>Have your submitted images open and ready to screen-share if asked</li><li>Prepare 1–2 specific questions about your workflow or results</li><li>Think about what technique surprised you most — positively or negatively</li></ul>"}'),
  (v_l2,'meeting',2,'{"meeting_id":"","title":"Live Session 3 — Mid-Course Project Review","start_time":""}'),
  (v_l2,'callout',3,'{"type":"info","title":"Session Guidelines","body":"Duration: 30 minutes. Join 2–3 minutes early to test your audio and camera. The session is recorded for students who cannot attend live — the recording will be available in this lesson within 24 hours of the session ending. If you have not yet submitted your project, you can still attend and participate in the Q&A portion."}'),
  (v_l2,'checklist',4,'{"items":["Project ZIP submitted at least 24 hours before the session","Stable internet connection tested","Camera and microphone working","Your edited images ready to screen-share","Questions written down in advance","Notebook ready for feedback you want to remember"]}');

  RAISE NOTICE '✓ Module 8 (Mid-Course Project) content loaded.';
END $$;
